package com.viettel.ocs.entity;
// Generated Sep 2, 2016 4:54:08 PM by Hibernate Tools 3.2.1.GA


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Transient;

/**
 * AcmBillCycle generated by hbm2java
 */
@Entity
@Table(name="acm_bill_cycle"
)
public class AcmBillCycle extends BaseEntity  implements java.io.Serializable {

	@Override
	@Transient
	public String getNodeName() {
		return null;
	}
		
	private Long domainId;
	@Column(name="DOMAIN_ID")
    public Long getDomainId() {
		return domainId;
	}
	public void setDomainId(Long domainId) {
		this.domainId = domainId;
	}

     private long acmBillCycleKey;
     private long acmBillCycleId;
     private Long balTypeId;
     private Long billingCycleTypeId;

    public AcmBillCycle() {
    }

	
    public AcmBillCycle(long acmBillCycleId) {
        this.acmBillCycleId = acmBillCycleId;
    }
    public AcmBillCycle(long acmBillCycleId, Long balTypeId, Long billingCycleTypeId) {
       this.acmBillCycleId = acmBillCycleId;
       this.balTypeId = balTypeId;
       this.billingCycleTypeId = billingCycleTypeId;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)
    
    @Column(name="ACM_BILL_CYCLE_KEY", unique=true, nullable=false)
    public long getAcmBillCycleKey() {
        return this.acmBillCycleKey;
    }
    
    public void setAcmBillCycleKey(long acmBillCycleKey) {
        this.acmBillCycleKey = acmBillCycleKey;
    }
    
    @Column(name="ACM_BILL_CYCLE_ID", nullable=false)
    public long getAcmBillCycleId() {
        return this.acmBillCycleId;
    }
    
    public void setAcmBillCycleId(long acmBillCycleId) {
        this.acmBillCycleId = acmBillCycleId;
    }
    
    @Column(name="BAL_TYPE_ID")
    public Long getBalTypeId() {
        return this.balTypeId;
    }
    
    public void setBalTypeId(Long balTypeId) {
        this.balTypeId = balTypeId;
    }
    
    @Column(name="BILLING_CYCLE_TYPE_ID")
    public Long getBillingCycleTypeId() {
        return this.billingCycleTypeId;
    }
    
    public void setBillingCycleTypeId(Long billingCycleTypeId) {
        this.billingCycleTypeId = billingCycleTypeId;
    }
}


