package com.viettel.ocs.entity;
// Generated Sep 2, 2016 4:54:08 PM by Hibernate Tools 3.2.1.GA

import static javax.persistence.GenerationType.IDENTITY;

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Transient;

/**
 * Action generated by hbm2java
 */
@Entity
@Table(name = "action")
public class Action extends BaseEntity implements java.io.Serializable, Cloneable {
	@Override
	@Transient
	public String getNodeName() {
		return actionName;
	}

	private Long domainId;

	@Column(name = "DOMAIN_ID")
	public Long getDomainId() {
		return domainId;
	}

	public void setDomainId(Long domainId) {
		this.domainId = domainId;
	}

	private long actionId;
	private String actionName;
	private Long actionType;
	private Long categoryId;
	private Long sortPriceComponentId;
	private Long dynamicReserveId;
	private String remark;
	private Long reserveinfoId;
	private Date effDate;
	private Date expDate;
	private Boolean state;
	private Long index;
	private Boolean generated;
	private Long priorityFilterId;

	public Action() {
	}

	public Action(String actionName, Long actionType, Long categoryId, Long sortPriceComponentId, Long dynamicReserveId,
			String remark) {
		this.actionName = actionName;
		this.actionType = actionType;
		this.categoryId = categoryId;
		this.sortPriceComponentId = sortPriceComponentId;
		this.dynamicReserveId = dynamicReserveId;
		this.remark = remark;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "ACTION_ID", unique = true, nullable = false)
	public long getActionId() {
		return this.actionId;
	}

	public void setActionId(long actionId) {
		this.actionId = actionId;
	}

	@Column(name = "ACTION_NAME", length = 65535)
	public String getActionName() {
		return this.actionName;
	}

	public void setActionName(String actionName) {
		this.actionName = actionName;
	}

	@Column(name = "ACTION_TYPE")
	public Long getActionType() {
		return this.actionType;
	}

	public void setActionType(Long actionType) {
		this.actionType = actionType;
	}

	@Column(name = "CATEGORY_ID")
	public Long getCategoryId() {
		return this.categoryId;
	}

	public void setCategoryId(Long categoryId) {
		this.categoryId = categoryId;
	}

	@Column(name = "SORT_PRICE_COMPONENT_ID")
	public Long getSortPriceComponentId() {
		return this.sortPriceComponentId;
	}

	public void setSortPriceComponentId(Long sortPriceComponentId) {
		this.sortPriceComponentId = sortPriceComponentId;
	}

	@Column(name = "DYNAMIC_RESERVE_ID")
	public Long getDynamicReserveId() {
		return this.dynamicReserveId;
	}

	public void setDynamicReserveId(Long dynamicReserveId) {
		this.dynamicReserveId = dynamicReserveId;
	}

	@Column(name = "REMARK", length = 20)
	public String getRemark() {
		return this.remark;
	}

	public void setRemark(String remark) {
		this.remark = remark;
	}

	@Column(name = "RESERVE_INFO_ID")
	public Long getReserveinfoId() {
		return reserveinfoId;
	}

	public void setReserveinfoId(Long reserveinfoId) {
		this.reserveinfoId = reserveinfoId;
	}

	@Column(name = "EFF_DATE")
	public Date getEffDate() {
		return effDate;
	}

	public void setEffDate(Date effDate) {
		this.effDate = effDate;
	}

	@Column(name = "EXP_DATE")
	public Date getExpDate() {
		return expDate;
	}

	public void setExpDate(Date expDate) {
		this.expDate = expDate;
	}

	@Column(name = "STATE")
	public Boolean getState() {
		return state;
	}

	public void setState(Boolean state) {
		this.state = state;
	}

	public Action clone() throws CloneNotSupportedException {
		return (Action) super.clone();
	}

	@Column(name = "POS_INDEX")
	public Long getIndex() {
		return index;
	}

	public void setIndex(Long index) {
		this.index = index;
	}

	@Column(name = "IS_GENERATED")
	public Boolean isGenerated() {
		return generated;
	}

	public void setGenerated(Boolean generated) {
		this.generated = generated;
	}

	@Column(name = "PRIORITY_FILTER_ID")
	public Long getPriorityFilterId() {
		return priorityFilterId;
	}

	public void setPriorityFilterId(Long priorityFilterId) {
		this.priorityFilterId = priorityFilterId;
	}

}
