package com.viettel.ocs.entity;
// Generated Sep 2, 2016 4:54:08 PM by Hibernate Tools 3.2.1.GA

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Transient;

/**
 * ActionType generated by hbm2java
 */
@SuppressWarnings("serial")
@Entity
@Table(name = "action_type")
public class ActionType extends BaseEntity implements java.io.Serializable ,Cloneable{

	@Override
	@Transient
	public String getNodeName() {
		return actionTypeName;
	}

//	private Long domainId;
//
//	@Column(name = "DOMAIN_ID")
//	public Long getDomainId() {
//		return domainId;
//	}
//
//	public void setDomainId(Long domainId) {
//		this.domainId = domainId;
//	}

	private Long actionTypeId;
	private String actionTypeName;
	private Long categoryId;
	private String remark;
	private String icon;
	private Long index;
	private Boolean forProvisioning;
	
	public ActionType() {
	}

	public ActionType(String actionTypeName, Long categoryId) {
		this.actionTypeName = actionTypeName;
		this.categoryId = categoryId;
	}

	@Id
//	@GeneratedValue(strategy = GenerationType.IDENTITY)
	@Column(name = "ACTION_TYPE_ID", unique = true, nullable = false)
	public Long getActionTypeId() {
		return this.actionTypeId;
	}

	public void setActionTypeId(Long actionTypeId) {
		this.actionTypeId = actionTypeId;
	}

	@Column(name = "ACTION_TYPE_NAME")
	public String getActionTypeName() {
		return this.actionTypeName;
	}

	public void setActionTypeName(String actionTypeName) {
		this.actionTypeName = actionTypeName;
	}

	@Column(name = "CATEGORY_ID")
	public Long getCategoryId() {
		return this.categoryId;
	}

	public void setCategoryId(Long categoryId) {
		this.categoryId = categoryId;
	}

	@Column(name = "ICON")
	public String getIcon() {
		return icon;
	}

	public void setIcon(String icon) {
		this.icon = icon;
	}

	@Column(name = "REMARK", length = 20)
	public String getRemark() {
		return this.remark;
	}

	public void setRemark(String remark) {
		this.remark = remark;
	}

	@Column(name = "POS_INDEX")
	public Long getIndex() {
		return index;
	}

	public void setIndex(Long index) {
		this.index = index;
	}
	
	@Column(name = "FOR_PROVISIONING")
	public Boolean getForProvisioning() {
		return forProvisioning;
	}

	public void setForProvisioning(Boolean forProvisioning) {
		this.forProvisioning = forProvisioning;
	}

	@Override
	public ActionType clone() throws CloneNotSupportedException {
		return (ActionType) super.clone();
	}
}
