package com.viettel.ocs.entity;
// Generated Sep 2, 2016 4:54:08 PM by Hibernate Tools 3.2.1.GA

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Transient;

/**
 * ActionPriceComponentMap generated by hbm2java
 */
@Entity
@Table(name = "action_price_component_map")
public class ActionPriceComponentMap extends BaseEntity implements java.io.Serializable {

	@Override
	@Transient
	public String getNodeName() {
		return null;
	}

	private Long domainId;

	@Column(name = "DOMAIN_ID")
	public Long getDomainId() {
		return domainId;
	}

	public void setDomainId(Long domainId) {
		this.domainId = domainId;
	}

	private long actionPriceComponentMapId;
	private Long actionId;
	private Long priceComponentId;
	private Long pcIndex;

	public ActionPriceComponentMap() {
	}

	public ActionPriceComponentMap(Long actionId, Long priceComponentId, Long pcIndex) {
		this.actionId = actionId;
		this.priceComponentId = priceComponentId;
		this.pcIndex = pcIndex;
	}

	public ActionPriceComponentMap(Long actionId, Long priceComponentId) {
		this.actionId = actionId;
		this.priceComponentId = priceComponentId;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "ACTION_PRICE_COMPONENT_MAP_ID", unique = true, nullable = false)
	public long getActionPriceComponentMapId() {
		return this.actionPriceComponentMapId;
	}

	public void setActionPriceComponentMapId(long actionPriceComponentMapId) {
		this.actionPriceComponentMapId = actionPriceComponentMapId;
	}

	@Column(name = "ACTION_ID")
	public Long getActionId() {
		return this.actionId;
	}

	public void setActionId(Long actionId) {
		this.actionId = actionId;
	}

	@Column(name = "PRICE_COMPONENT_ID")
	public Long getPriceComponentId() {
		return this.priceComponentId;
	}

	public void setPriceComponentId(Long priceComponentId) {
		this.priceComponentId = priceComponentId;
	}

	@Column(name = "PC_INDEX")
	public Long getPcIndex() {
		return this.pcIndex;
	}

	public void setPcIndex(Long pcIndex) {
		this.pcIndex = pcIndex;
	}

}
