package com.viettel.ocs.entity;
// Generated Sep 2, 2016 4:54:08 PM by Hibernate Tools 3.2.1.GA

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.Transient;

/**
 * BalType generated by hbm2java
 */
@Entity
@Table(name = "bal_type")
public class BalType extends BaseEntity implements java.io.Serializable, Cloneable {

	@Override
	@Transient
	public String getNodeName() {
		return this.balTypeName;
	}

	private Long domainId;

	@Column(name = "DOMAIN_ID")
	public Long getDomainId() {
		return domainId;
	}

	public void setDomainId(Long domainId) {
		this.domainId = domainId;
	}

	private long balTypeId;
	private String balTypeName;
	private String description;
	private String externalId;
	private Long balTypeType;
	private Long categoryId;
	private Long paymentType;
	private String isCurrency;
	private Long balTypepercision;
	private Long effDateType;
	private Date effDate;
	private Long expDateType;
	private Date expDate;
	private Long recuringType;
	private Long recuringPeriod;
	private Boolean isAcm;
	private Long unitTypeId;
	private Long periodicPeriodType;
	private Long periodicPeriod;
	private Long windowSize;
	private Long lowWaterMarkLevel;
	private Long highWaterMarkLevel;
	private Long billingCycleTypeId;
	private Long balLevel;
	private Boolean isClearable;
	private Long expDateData;
	private Long effDateData;
	private Long index;

	public BalType() {
	}

	public BalType(String balTypeName, String description, String externalId, Long balTypeType, Long categoryId,
			Long paymentType, String isCurrency, Long balTypepercision, Long effDateType, Date effDate,
			Long expDateType, Date expDate, Long recuringType, Long recuringPeriod, Boolean isAcm, Long unitTypeId,
			Long periodicPeriodType, Long periodicPeriod, Long windowSize, Long lowWaterMarkLevel,
			Long highWaterMarkLevel, Long billingCycleTypeId, Long balLevel, Boolean isClearable, Long expDateData,
			Long effDateData, Long index) {
		this.balTypeName = balTypeName;
		this.description = description;
		this.externalId = externalId;
		this.balTypeType = balTypeType;
		this.categoryId = categoryId;
		this.paymentType = paymentType;
		this.isCurrency = isCurrency;
		this.balTypepercision = balTypepercision;
		this.effDateType = effDateType;
		this.effDate = effDate;
		this.expDateType = expDateType;
		this.expDate = expDate;
		this.recuringType = recuringType;
		this.recuringPeriod = recuringPeriod;
		this.isAcm = isAcm;
		this.unitTypeId = unitTypeId;
		this.periodicPeriodType = periodicPeriodType;
		this.periodicPeriod = periodicPeriod;
		this.windowSize = windowSize;
		this.lowWaterMarkLevel = lowWaterMarkLevel;
		this.highWaterMarkLevel = highWaterMarkLevel;
		this.billingCycleTypeId = billingCycleTypeId;
		this.balLevel = balLevel;
		this.isClearable = isClearable;
		this.expDateData = expDateData;
		this.effDateData = effDateData;
		this.index = index;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "BAL_TYPE_ID", nullable = false)
	public long getBalTypeId() {
		return this.balTypeId;
	}

	public void setBalTypeId(long balTypeId) {
		this.balTypeId = balTypeId;
	}

	@Column(name = "BAL_TYPE_NAME", length = 65535)
	public String getBalTypeName() {
		return this.balTypeName;
	}

	public void setBalTypeName(String balTypeName) {
		this.balTypeName = balTypeName;
	}

	@Column(name = "DESCRIPTION", length = 65535)
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@Column(name = "EXTERNAL_ID", length = 65535)
	public String getExternalId() {
		return this.externalId;
	}

	public void setExternalId(String externalId) {
		this.externalId = externalId;
	}

	@Column(name = "BAL_TYPE_TYPE")
	public Long getBalTypeType() {
		return this.balTypeType;
	}

	public void setBalTypeType(Long balTypeType) {
		this.balTypeType = balTypeType;
	}

	@Column(name = "CATEGORY_ID")
	public Long getCategoryId() {
		return this.categoryId;
	}

	public void setCategoryId(Long categoryId) {
		this.categoryId = categoryId;
	}

	@Column(name = "PAYMENT_TYPE")
	public Long getPaymentType() {
		return this.paymentType;
	}

	public void setPaymentType(Long paymentType) {
		this.paymentType = paymentType;
	}

	@Column(name = "IS_CURRENCY", length = 20)
	public String getIsCurrency() {
		return this.isCurrency;
	}

	public void setIsCurrency(String isCurrency) {
		this.isCurrency = isCurrency;
	}

	@Column(name = "BAL_TYPE_PERCISION")
	public Long getBalTypepercision() {
		return balTypepercision;
	}

	public void setBalTypepercision(Long balTypepercision) {
		this.balTypepercision = balTypepercision;
	}

	@Column(name = "EFF_DATE_TYPE")
	public Long getEffDateType() {
		return this.effDateType;
	}

	public void setEffDateType(Long effDateType) {
		this.effDateType = effDateType;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "EFF_DATE", length = 19)
	public Date getEffDate() {
		return this.effDate;
	}

	public void setEffDate(Date effDate) {
		this.effDate = effDate;
	}

	@Column(name = "EXP_DATE_TYPE")
	public Long getExpDateType() {
		return this.expDateType;
	}

	public void setExpDateType(Long expDateType) {
		this.expDateType = expDateType;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "EXP_DATE", length = 19)
	public Date getExpDate() {
		return this.expDate;
	}

	public void setExpDate(Date expDate) {
		this.expDate = expDate;
	}

	@Column(name = "RECURING_TYPE")
	public Long getRecuringType() {
		return this.recuringType;
	}

	public void setRecuringType(Long recuringType) {
		this.recuringType = recuringType;
	}

	@Column(name = "RECURING_PERIOD")
	public Long getRecuringPeriod() {
		return this.recuringPeriod;
	}

	public void setRecuringPeriod(Long recuringPeriod) {
		this.recuringPeriod = recuringPeriod;
	}

	@Column(name = "IS_ACM")
	public Boolean getIsAcm() {
		return this.isAcm;
	}

	public void setIsAcm(Boolean isAcm) {
		this.isAcm = isAcm;
	}

	@Column(name = "UNIT_TYPE_ID")
	public Long getUnitTypeId() {
		return this.unitTypeId;
	}

	public void setUnitTypeId(Long unitTypeId) {
		this.unitTypeId = unitTypeId;
	}

	@Column(name = "PERIODIC_PERIOD_TYPE")
	public Long getPeriodicPeriodType() {
		return this.periodicPeriodType;
	}

	public void setPeriodicPeriodType(Long periodicPeriodType) {
		this.periodicPeriodType = periodicPeriodType;
	}

	@Column(name = "PERIODIC_PERIOD")
	public Long getPeriodicPeriod() {
		return this.periodicPeriod;
	}

	public void setPeriodicPeriod(Long periodicPeriod) {
		this.periodicPeriod = periodicPeriod;
	}

	@Column(name = "WINDOW_SIZE")
	public Long getWindowSize() {
		return this.windowSize;
	}

	public void setWindowSize(Long windowSize) {
		this.windowSize = windowSize;
	}

	@Column(name = "LOW_WATER_MARK_LEVEL")
	public Long getLowWaterMarkLevel() {
		return this.lowWaterMarkLevel;
	}

	public void setLowWaterMarkLevel(Long lowWaterMarkLevel) {
		this.lowWaterMarkLevel = lowWaterMarkLevel;
	}

	@Column(name = "HIGH_WATER_MARK_LEVEL")
	public Long getHighWaterMarkLevel() {
		return this.highWaterMarkLevel;
	}

	public void setHighWaterMarkLevel(Long highWaterMarkLevel) {
		this.highWaterMarkLevel = highWaterMarkLevel;
	}

	@Column(name = "BILLING_CYCLE_TYPE_ID")
	public Long getBillingCycleTypeId() {
		return this.billingCycleTypeId;
	}

	public void setBillingCycleTypeId(Long billingCycleTypeId) {
		this.billingCycleTypeId = billingCycleTypeId;
	}

	@Column(name = "BAL_LEVEL")
	public Long getBalLevel() {
		return this.balLevel;
	}

	public void setBalLevel(Long balLevel) {
		this.balLevel = balLevel;
	}

	@Column(name = "IS_CLEARABLE")
	public Boolean getIsClearable() {
		return this.isClearable;
	}

	public void setIsClearable(Boolean isCleanable) {
		this.isClearable = isCleanable;
	}

	@Column(name = "EXP_DATE_DATA")
	public Long getExpDateData() {
		return expDateData;
	}

	public void setExpDateData(Long expDateData) {
		this.expDateData = expDateData;
	}

	@Column(name = "EFF_DATE_DATA")
	public Long getEffDateData() {
		return effDateData;
	}

	public void setEffDateData(Long effDateData) {
		this.effDateData = effDateData;
	}

	@Column(name = "POS_INDEX", length = 20)
	public Long getIndex() {
		return index;
	}

	public void setIndex(Long index) {
		this.index = index;
	}

	@Override
	public BalType clone() throws CloneNotSupportedException {
		// TODO Auto-generated method stub
		return (BalType) super.clone();
	}

}
