package com.viettel.ocs.entity;
// Generated Sep 2, 2016 4:54:08 PM by Hibernate Tools 3.2.1.GA


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.Transient;

/**
 * BillingCycle generated by hbm2java
 */
@Entity
@Table(name="billing_cycle"
)
public class BillingCycle extends BaseEntity  implements java.io.Serializable {

	@Override
	@Transient
	public String getNodeName() {
		return null;
	}
	private Long domainId;
	@Column(name="DOMAIN_ID")
    public Long getDomainId() {
		return domainId;
	}
	public void setDomainId(Long domainId) {
		this.domainId = domainId;
	}
     private long billingCycleId;
     private Long billingCycleTypeId;
     private Date cycleBeginDate;
     private Date cycleEndDate;
     private Long state;

    public BillingCycle() {
    }

    public BillingCycle(Long billingCycleTypeId, Date cycleBeginDate, Date cycleEndDate, Long state) {
       this.billingCycleTypeId = billingCycleTypeId;
       this.cycleBeginDate = cycleBeginDate;
       this.cycleEndDate = cycleEndDate;
       this.state = state;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)
    
    @Column(name="BILLING_CYCLE_ID", unique=true, nullable=false)
    public long getBillingCycleId() {
        return this.billingCycleId;
    }
    
    public void setBillingCycleId(long billingCycleId) {
        this.billingCycleId = billingCycleId;
    }
    
    @Column(name="BILLING_CYCLE_TYPE_ID")
    public Long getBillingCycleTypeId() {
        return this.billingCycleTypeId;
    }
    
    public void setBillingCycleTypeId(Long billingCycleTypeId) {
        this.billingCycleTypeId = billingCycleTypeId;
    }
    @Temporal(TemporalType.DATE)
    @Column(name="CYCLE_BEGIN_DATE", length=19)
    public Date getCycleBeginDate() {
        return this.cycleBeginDate;
    }
    
    public void setCycleBeginDate(Date cycleBeginDate) {
        this.cycleBeginDate = cycleBeginDate;
    }
    @Temporal(TemporalType.DATE)
    @Column(name="CYCLE_END_DATE", length=19)
    public Date getCycleEndDate() {
        return this.cycleEndDate;
    }
    
    public void setCycleEndDate(Date cycleEndDate) {
        this.cycleEndDate = cycleEndDate;
    }
    
    @Column(name="STATE")
    public Long getState() {
        return this.state;
    }
    
    public void setState(Long state) {
        this.state = state;
    }




}


