package com.viettel.ocs.entity;
// Generated Sep 2, 2016 4:54:08 PM by Hibernate Tools 3.2.1.GA

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.Transient;

/**
 * BillingCycleType generated by hbm2java
 */
@Entity
@Table(name = "billing_cycle_type")
public class BillingCycleType extends BaseEntity implements java.io.Serializable {

	@Override
	@Transient
	public String getNodeName() {
		return this.billingCycleTypeName;
	}

	private Long domainId;

	@Column(name = "DOMAIN_ID")
	public Long getDomainId() {
		return domainId;
	}

	public void setDomainId(Long domainId) {
		this.domainId = domainId;
	}

	private long billingCycleTypeId;
	private Long calcUnitId;
	private String billingCycleTypeName;
	private Long quantity;
	private Date beginDate = new Date();
	private String remark;
	private Long categoryId;
	private Integer fromOfDay;
	private Long index;

	public BillingCycleType() {
	}

	public BillingCycleType(Long calcUnitId, String billingCycleTypeName, Long quantity, Date beginDate, String remark,
			Long categoryId) {
		this.calcUnitId = calcUnitId;
		this.billingCycleTypeName = billingCycleTypeName;
		this.quantity = quantity;
		this.beginDate = beginDate;
		this.remark = remark;
		this.categoryId = categoryId;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "BILLING_CYCLE_TYPE_ID", unique = true, nullable = false)
	public long getBillingCycleTypeId() {
		return this.billingCycleTypeId;
	}

	public void setBillingCycleTypeId(long billingCycleTypeId) {
		this.billingCycleTypeId = billingCycleTypeId;
	}

	@Column(name = "CALC_UNIT_ID")
	public Long getCalcUnitId() {
		return this.calcUnitId;
	}

	public void setCalcUnitId(Long calcUnitId) {
		this.calcUnitId = calcUnitId;
	}

	@Column(name = "BILLING_CYCLE_TYPE_NAME", length = 60)
	public String getBillingCycleTypeName() {
		return this.billingCycleTypeName;
	}

	public void setBillingCycleTypeName(String billingCycleTypeName) {
		this.billingCycleTypeName = billingCycleTypeName;
	}

	@Column(name = "QUANTITY")
	public Long getQuantity() {
		return this.quantity;
	}

	public void setQuantity(Long quantity) {
		this.quantity = quantity;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "BEGIN_DATE", length = 19)
	public Date getBeginDate() {
		return this.beginDate;
	}

	public void setBeginDate(Date beginDate) {
		this.beginDate = beginDate;
	}

	@Column(name = "REMARK", length = 250)
	public String getRemark() {
		return this.remark;
	}

	public void setRemark(String remark) {
		this.remark = remark;
	}

	@Column(name = "CATEGORY_ID")
	public Long getCategoryId() {
		return this.categoryId;
	}

	public void setCategoryId(Long categoryId) {
		this.categoryId = categoryId;
	}

	@Column(name = "FROM_OF_DAY")
	public Integer getFromOfDay() {
		return fromOfDay;
	}

	public void setFromOfDay(Integer fromOfDay) {
		this.fromOfDay = fromOfDay;
	}

	@Column(name = "POS_INDEX")
	public Long getIndex() {
		return index;
	}

	public void setIndex(Long index) {
		this.index = index;
	}

}
