package com.viettel.ocs.entity;
// Generated Sep 2, 2016 4:54:08 PM by Hibernate Tools 3.2.1.GA

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Transient;

/**
 * Block generated by hbm2java
 */
@Entity
@Table(name = "block")
public class Block extends BaseEntity implements java.io.Serializable, Cloneable {

	@Override
	@Transient
	public String getNodeName() {
		return this.blockName;
	}

	private Long domainId;

	@Column(name = "DOMAIN_ID")
	public Long getDomainId() {
		return domainId;
	}

	public void setDomainId(Long domainId) {
		this.domainId = domainId;
	}

	private long blockId;
	private Long blockType;
	private Long categoryId;
	private String blockName;
	private Boolean isUseSpecialMethod;
	private Boolean isCreateNewBalance;
	private Long affectedObjectType;
	private Long affectedValue;
	private String affectedField;
	private String remark;
	private Long index;
	private Boolean isApplyForNullEffDate;
	private Boolean generated;
	private Long blockFilterId;

	public Block() {
	}

	public Block(Long blockType, Long categoryId, String blockName, Boolean isUseSpecialMethod,
			Boolean isCreateNewBalance, Long affectedObjectType, Long affectedValue, String affectedField,
			String remark) {
		this.blockType = blockType;
		this.categoryId = categoryId;
		this.blockName = blockName;
		this.isUseSpecialMethod = isUseSpecialMethod;
		this.isCreateNewBalance = isCreateNewBalance;
		this.affectedObjectType = affectedObjectType;
		this.affectedValue = affectedValue;
		this.affectedField = affectedField;
		this.remark = remark;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "BLOCK_ID", unique = true, nullable = false)
	public long getBlockId() {
		return this.blockId;
	}

	public void setBlockId(long blockId) {
		this.blockId = blockId;
	}

	@Column(name = "BLOCK_TYPE")
	public Long getBlockType() {
		return this.blockType;
	}

	public void setBlockType(Long blockType) {
		this.blockType = blockType;
	}

	@Column(name = "CATEGORY_ID")
	public Long getCategoryId() {
		return this.categoryId;
	}

	public void setCategoryId(Long categoryId) {
		this.categoryId = categoryId;
	}

	@Column(name = "BLOCK_NAME", length = 65535)
	public String getBlockName() {
		return this.blockName;
	}

	public void setBlockName(String blockName) {
		this.blockName = blockName;
	}

	@Column(name = "IS_USE_SPECIAL_METHOD")
	public Boolean getIsUseSpecialMethod() {
		return this.isUseSpecialMethod;
	}

	public void setIsUseSpecialMethod(Boolean isUseSpecialMethod) {
		this.isUseSpecialMethod = isUseSpecialMethod;
	}

	@Column(name = "IS_CREATE_NEW_BALANCE")
	public Boolean getIsCreateNewBalance() {
		return this.isCreateNewBalance;
	}

	public void setIsCreateNewBalance(Boolean isCreateNewBalance) {
		this.isCreateNewBalance = isCreateNewBalance;
	}

	@Column(name = "AFFECTED_OBJECT_TYPE")
	public Long getAffectedObjectType() {
		return this.affectedObjectType;
	}

	public void setAffectedObjectType(Long affectedObjectType) {
		this.affectedObjectType = affectedObjectType;
	}

	@Column(name = "AFFECTED_VALUE")
	public Long getAffectedValue() {
		return this.affectedValue;
	}

	public void setAffectedValue(Long affectedValue) {
		this.affectedValue = affectedValue;
	}

	@Column(name = "AFFECTED_FIELD", length = 65535)
	public String getAffectedField() {
		return this.affectedField;
	}

	public void setAffectedField(String affectedField) {
		this.affectedField = affectedField;
	}

	@Column(name = "REMARK", length = 65535)
	public String getRemark() {
		return this.remark;
	}

	public void setRemark(String remark) {
		this.remark = remark;
	}

	@Column(name = "POS_INDEX")
	public Long getIndex() {
		return index;
	}

	public void setIndex(Long index) {
		this.index = index;
	}

	@Column(name = "IS_APPLY_FOR_NULL_EFFDATE")
	public Boolean getIsApplyForNullEffDate() {
		return isApplyForNullEffDate;
	}

	public void setIsApplyForNullEffDate(Boolean isApplyForNullEffDate) {
		this.isApplyForNullEffDate = isApplyForNullEffDate;
	}

	@Column(name = "IS_GENERATED")
	public Boolean isGenerated() {
		return generated;
	}

	public void setGenerated(Boolean generated) {
		this.generated = generated;
	}

	@Column(name = "BLOCK_FILTER_ID")
	public Long getBlockFilterId() {
		return blockFilterId;
	}

	public void setBlockFilterId(Long blockFilterId) {
		this.blockFilterId = blockFilterId;
	}

	@Override
	public Block clone() throws CloneNotSupportedException {
		return (Block) super.clone();
	}

}
