package com.viettel.ocs.entity;
// Generated Sep 2, 2016 4:54:08 PM by Hibernate Tools 3.2.1.GA

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Transient;

/**
 * BlockRateTableMap generated by hbm2java
 */
@Entity
@Table(name = "block_rate_table_map")
public class BlockRateTableMap extends BaseEntity implements java.io.Serializable, Cloneable {

	@Override
	@Transient
	public String getNodeName() {
		return null;
	}

	private Long domainId;

	@Column(name = "DOMAIN_ID")
	public Long getDomainId() {
		return domainId;
	}

	public void setDomainId(Long domainId) {
		this.domainId = domainId;
	}

	private long blockRateTableMapId;
	private Long blockId;
	private Long rateTableId;
	private Long componentType;
	private Long rateTableIndex;

	public BlockRateTableMap() {
	}

	public BlockRateTableMap(Long blockId, Long rateTableId, Long componentType, Long rateTableIndex) {
		this.blockId = blockId;
		this.rateTableId = rateTableId;
		this.componentType = componentType;
		this.rateTableIndex = rateTableIndex;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "BLOCK_RATE_TABLE_MAP_ID", unique = true, nullable = false)
	public long getBlockRateTableMapId() {
		return this.blockRateTableMapId;
	}

	public void setBlockRateTableMapId(long blockRateTableMapId) {
		this.blockRateTableMapId = blockRateTableMapId;
	}

	@Column(name = "BLOCK_ID")
	public Long getBlockId() {
		return this.blockId;
	}

	public void setBlockId(Long blockId) {
		this.blockId = blockId;
	}

	@Column(name = "RATE_TABLE_ID")
	public Long getRateTableId() {
		return this.rateTableId;
	}

	public void setRateTableId(Long rateTableId) {
		this.rateTableId = rateTableId;
	}

	@Column(name = "COMPONENT_TYPE")
	public Long getComponentType() {
		return this.componentType;
	}

	public void setComponentType(Long componentType) {
		this.componentType = componentType;
	}

	@Column(name = "RATE_TABLE_INDEX")
	public Long getRateTableIndex() {
		return this.rateTableIndex;
	}

	public void setRateTableIndex(Long rateTableIndex) {
		this.rateTableIndex = rateTableIndex;
	}

	@Override
	public BlockRateTableMap clone() throws CloneNotSupportedException {
		return (BlockRateTableMap) super.clone();
	}

}
