package com.viettel.ocs.entity;
// Generated Sep 2, 2016 4:54:08 PM by Hibernate Tools 3.2.1.GA

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Transient;

/**
 * CalcUnit generated by hbm2java
 */
@Entity
@Table(name = "calc_unit")
public class CalcUnit extends BaseEntity implements java.io.Serializable {

	@Override
	@Transient
	public String getNodeName() {
		return null;
	}
	private long calcUnitId;
	private String calcUnitName;
	private Long calcUnitType;
	private String remark;

	public CalcUnit() {
	}

	public CalcUnit(String calcUnitName, Long calcUnitType, String remark) {
		this.calcUnitName = calcUnitName;
		this.calcUnitType = calcUnitType;
		this.remark = remark;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "CALC_UNIT_ID", unique = true, nullable = false)
	public long getCalcUnitId() {
		return this.calcUnitId;
	}

	public void setCalcUnitId(long calcUnitId) {
		this.calcUnitId = calcUnitId;
	}

	@Column(name = "CALC_UNIT_NAME", length = 65535)
	public String getCalcUnitName() {
		return this.calcUnitName;
	}

	public void setCalcUnitName(String calcUnitName) {
		this.calcUnitName = calcUnitName;
	}

	@Column(name = "CALC_UNIT_TYPE")
	public Long getCalcUnitType() {
		return this.calcUnitType;
	}

	public void setCalcUnitType(Long calcUnitType) {
		this.calcUnitType = calcUnitType;
	}

	@Column(name = "REMARK", length = 65535)
	public String getRemark() {
		return this.remark;
	}

	public void setRemark(String remark) {
		this.remark = remark;
	}

}
