package com.viettel.ocs.entity;
// Generated Sep 2, 2016 4:54:08 PM by Hibernate Tools 3.2.1.GA


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Transient;

/**
 * Category generated by hbm2java
 */
@Entity
@Table(name="category"
)
public class Category extends BaseEntity  implements java.io.Serializable {

	@Override
	@Transient
	public String getNodeName() {
		return this.categoryName;
	}
	private Long domainId;
	@Column(name="DOMAIN_ID")
    public Long getDomainId() {
		return domainId;
	}
	public void setDomainId(Long domainId) {
		this.domainId = domainId;
	}
     private long categoryId;
     private Long categoryType;
     private String categoryName;
     private Long categoryParentId;
     private String remark;
     private String treeType;
     private String path;
 	 private Long posIndex;

    public Category() {
    }

    public Category(Long categoryType, String categoryName, Long categoryParentId, String remark) {
       this.categoryType = categoryType;
       this.categoryName = categoryName;
       this.categoryParentId = categoryParentId;
       this.remark = remark;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)
    
    @Column(name="CATEGORY_ID", unique=true, nullable=false)
    public long getCategoryId() {
        return this.categoryId;
    }
    
    public void setCategoryId(long categoryId) {
        this.categoryId = categoryId;
    }
    
    @Column(name="CATEGORY_TYPE")
    public Long getCategoryType() {
        return this.categoryType;
    }
    
    public void setCategoryType(Long categoryType) {
        this.categoryType = categoryType;
    }
    
    @Column(name="CATEGORY_NAME", length=65535)
    public String getCategoryName() {
        return this.categoryName;
    }
    
    public void setCategoryName(String categoryName) {
        this.categoryName = categoryName;
    }
    
    @Column(name="CATEGORY_PARENT_ID")
    public Long getCategoryParentId() {
        return this.categoryParentId;
    }
    
    public void setCategoryParentId(Long categoryParentId) {
        this.categoryParentId = categoryParentId;
    }
    
    @Column(name="REMARK", length=65535)
    public String getRemark() {
        return this.remark;
    }
    
    public void setRemark(String remark) {
        this.remark = remark;
    }

	public String getTreeType() {
		return treeType;
	}

	public void setTreeType(String treeType) {
		this.treeType = treeType;
	}
	
	public String getPath() {
		return path;
	}
	public void setPath(String path) {
		this.path = path;
	}
	
	@Column(name="pos_index")
	public Long getPosIndex() {
		return posIndex;
	}

	public void setPosIndex(Long posIndex) {
		this.posIndex = posIndex;
	}
}


