package com.viettel.ocs.entity;
// Generated Sep 2, 2016 4:54:08 PM by Hibernate Tools 3.2.1.GA


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Transient;

/**
 * CssUssdResponse generated by hbm2java
 */
@Entity
@Table(name="css_ussd_response"
)
public class CssUssdResponse extends BaseEntity  implements java.io.Serializable, Cloneable {

	@Override
	@Transient
	public String getNodeName() {
		return this.name;
	}
	private Long domainId;
	@Column(name="DOMAIN_ID")
    public Long getDomainId() {
		return domainId;
	}
	public void setDomainId(Long domainId) {
		this.domainId = domainId;
	}
	
     private long cssUssdResponseId;
     private String content;
     private Long ussdResponseId;
     private String offerExternalId;
     private Long langId;
     private Long errorCode;
     private String name;
     private String remark;
     private Long categoryId;
     private Long posIndex;
     

    public CssUssdResponse() {
    }
    
     public CssUssdResponse(Long domainId, long cssUssdResponseId, String content, Long ussdResponseId,
    		 String offerExternalId, Long langId, Long errorCode, String name, String remark, Long categoryId,
			Long posIndex) {
		super();
		this.domainId = domainId;
		this.cssUssdResponseId = cssUssdResponseId;
		this.content = content;
		this.ussdResponseId = ussdResponseId;
		this.offerExternalId = offerExternalId;
		this.langId = langId;
		this.errorCode = errorCode;
		this.name = name;
		this.remark = remark;
		this.categoryId = categoryId;
		this.posIndex = posIndex;
	}
	@Id @GeneratedValue(strategy=IDENTITY)
    
    @Column(name="CSS_USSD_RESPONSE_ID", unique=true, nullable=false)
    public long getCssUssdResponseId() {
        return this.cssUssdResponseId;
    }
    
    public void setCssUssdResponseId(long cssUssdResponseId) {
        this.cssUssdResponseId = cssUssdResponseId;
    }
    
    @Column(name="CONTENT", length=20)
    public String getContent() {
        return this.content;
    }
    
    public void setContent(String content) {
        this.content = content;
    }
    
    @Column(name="USSD_RESPONSE_ID")
    public Long getUssdResponseId() {
        return this.ussdResponseId;
    }
    
    public void setUssdResponseId(Long ussdResponseId) {
        this.ussdResponseId = ussdResponseId;
    }
    
    @Column(name="OFFER_EXTERNAL_ID")
    public String getOfferExternalId() {
        return this.offerExternalId;
    }
    
    public void setOfferExternalId(String offerExternalId) {
        this.offerExternalId = offerExternalId;
    }
    
    @Column(name="LANG_ID")
    public Long getLangId() {
        return this.langId;
    }
    
    public void setLangId(Long langId) {
        this.langId = langId;
    }
    
    @Column(name="ERROR_CODE")
    public Long getErrorCode() {
        return this.errorCode;
    }
    
    public void setErrorCode(Long errorCode) {
        this.errorCode = errorCode;
    }
    
    @Column(name="NAME")
	public String getName() {
		return name;
	}
	public void setName(String name) {
		this.name = name;
	}
	
	@Column(name="REMARK")
	public String getRemark() {
		return remark;
	}
	public void setRemark(String remark) {
		this.remark = remark;
	}
	
	@Column(name="CATEGORY_ID")
	public Long getCategoryId() {
		return categoryId;
	}
	public void setCategoryId(Long categoryId) {
		this.categoryId = categoryId;
	}
	
	@Column(name="POS_INDEX")
	public Long getPosIndex() {
		return posIndex;
	}
	public void setPosIndex(Long posIndex) {
		this.posIndex = posIndex;
	}
	
	@Override
	public CssUssdResponse clone() throws CloneNotSupportedException {
		// TODO Auto-generated method stub
		return (CssUssdResponse) super.clone();
	}
    
}


