package com.viettel.ocs.entity;
// Generated Sep 2, 2016 4:54:08 PM by Hibernate Tools 3.2.1.GA

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Transient;

/**
 * DecisionTable generated by hbm2java
 */
@Entity
@Table(name = "decision_table")
public class DecisionTable extends BaseEntity implements java.io.Serializable, Cloneable {

	@Override
	@Transient
	public String getNodeName() {
		return this.decisionTableName;
	}

	private Long domainId;

	@Column(name = "DOMAIN_ID")
	public Long getDomainId() {
		return domainId;
	}

	public void setDomainId(Long domainId) {
		this.domainId = domainId;
	}

	private long decisionTableId;
	private String decisionTableName;
	private Long defaultFormulaIndex;
	private String remark;
	private Long categoryId;
	private Long index;
	private Boolean generated;

	public DecisionTable() {
	}

	public DecisionTable(String decisionTableName, Long defaultFormulaIndex, String remark, Long categoryId) {
		this.decisionTableName = decisionTableName;
		this.defaultFormulaIndex = defaultFormulaIndex;
		this.remark = remark;
		this.categoryId = categoryId;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "DECISION_TABLE_ID", unique = true, nullable = false)
	public long getDecisionTableId() {
		return this.decisionTableId;
	}

	public void setDecisionTableId(long decisionTableId) {
		this.decisionTableId = decisionTableId;
	}

	@Column(name = "DECISION_TABLE_NAME", length = 65535)
	public String getDecisionTableName() {
		return this.decisionTableName;
	}

	public void setDecisionTableName(String decisionTableName) {
		this.decisionTableName = decisionTableName;
	}

	@Column(name = "DEFAULT_FORMULA_INDEX")
	public Long getDefaultFormulaIndex() {
		return this.defaultFormulaIndex;
	}

	public void setDefaultFormulaIndex(Long defaultFormulaIndex) {
		this.defaultFormulaIndex = defaultFormulaIndex;
	}

	@Column(name = "REMARK", length = 65535)
	public String getRemark() {
		return this.remark;
	}

	public void setRemark(String remark) {
		this.remark = remark;
	}

	@Column(name = "CATEGORY_ID")
	public Long getCategoryId() {
		return this.categoryId;
	}

	public void setCategoryId(Long categoryId) {
		this.categoryId = categoryId;
	}

	@Column(name = "POS_INDEX")
	public Long getIndex() {
		return index;
	}

	public void setIndex(Long index) {
		this.index = index;
	}

	@Column(name = "IS_GENERATED")
	public Boolean isGenerated() {
		return generated;
	}

	public void setGenerated(Boolean generated) {
		this.generated = generated;
	}

	@Override
	public DecisionTable clone() {
		try {
			return (DecisionTable) super.clone();
		} catch (CloneNotSupportedException e) {
			
			return this;
		}
	}

}
