package com.viettel.ocs.entity;
// Generated Sep 2, 2016 4:54:08 PM by Hibernate Tools 3.2.1.GA

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;

import java.time.chrono.ChronoLocalDate;

import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Transient;

/**
 * DynamicReserve generated by hbm2java
 */
@Entity
@Table(name = "dynamic_reserve")
public class DynamicReserve extends BaseEntity implements java.io.Serializable, Cloneable {

	@Override
	@Transient
	public String getNodeName() {
		return this.dynamicReserveName;
	}

	private Long domainId;

	@Column(name = "DOMAIN_ID")
	public Long getDomainId() {
		return domainId;
	}

	public void setDomainId(Long domainId) {
		this.domainId = domainId;
	}

	private long dynamicReserveId;
	private String dynamicReserveName;
	private Long categoryId;
	private String remark;
	private Long posIndex;
	private Boolean generated;

	public DynamicReserve() {
	}

	public DynamicReserve(String dynamicReserveName, Long categoryId, String remark) {
		this.dynamicReserveName = dynamicReserveName;
		this.categoryId = categoryId;
		this.remark = remark;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "DYNAMIC_RESERVE_ID", unique = true, nullable = false)
	public long getDynamicReserveId() {
		return this.dynamicReserveId;
	}

	public void setDynamicReserveId(long dynamicReserveId) {
		this.dynamicReserveId = dynamicReserveId;
	}

	@Column(name = "DYNAMIC_RESERVE_NAME", length = 65535)
	public String getDynamicReserveName() {
		return this.dynamicReserveName;
	}

	public void setDynamicReserveName(String dynamicReserveName) {
		this.dynamicReserveName = dynamicReserveName;
	}

	@Column(name = "CATEGORY_ID")
	public Long getCategoryId() {
		return this.categoryId;
	}

	public void setCategoryId(Long categoryId) {
		this.categoryId = categoryId;
	}

	@Column(name = "REMARK", length = 65535)
	public String getRemark() {
		return this.remark;
	}

	public void setRemark(String remark) {
		this.remark = remark;
	}

	@Override
	public DynamicReserve clone() throws CloneNotSupportedException {
		return (DynamicReserve) super.clone();
	}

	@Column(name = "POS_INDEX")
	public Long getPosIndex() {
		return posIndex;
	}

	public void setPosIndex(Long index) {
		this.posIndex = index;
	}

	@Column(name = "IS_GENERATED")
	public Boolean isGenerated() {
		return generated;
	}

	public void setGenerated(Boolean generated) {
		this.generated = generated;
	}
}
