package com.viettel.ocs.entity;
// Generated Sep 2, 2016 4:54:08 PM by Hibernate Tools 3.2.1.GA

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Transient;

/**
 * EventActionTypeMap generated by hbm2java
 */
@Entity
@Table(name = "event_action_type_map")
public class EventActionTypeMap extends BaseEntity implements java.io.Serializable {

	@Override
	@Transient
	public String getNodeName() {
		return null;
	}

//	private Long domainId;
//
//	@Column(name = "DOMAIN_ID")
//	public Long getDomainId() {
//		return domainId;
//	}
//
//	public void setDomainId(Long domainId) {
//		this.domainId = domainId;
//	}

	private long eventActionTypeMapId;
	private Long eventId;
	private Long actionTypeId;
	private Long actionTypeIndex;

	public EventActionTypeMap() {
	}

	public EventActionTypeMap(Long eventId, Long actionTypeId) {
		this.eventId = eventId;
		this.actionTypeId = actionTypeId;
	}

//	public EventActionTypeMap(Long eventId, Long actionTypeId, Long domainId) {
//		this.eventId = eventId;
//		this.actionTypeId = actionTypeId;
//		this.domainId = domainId;
//	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "EVENT_ACTION_TYPE_MAP_ID", unique = true, nullable = false)
	public long getEventActionTypeMapId() {
		return this.eventActionTypeMapId;
	}

	public void setEventActionTypeMapId(long eventActionTypeMapId) {
		this.eventActionTypeMapId = eventActionTypeMapId;
	}

	@Column(name = "EVENT_ID")
	public Long getEventId() {
		return this.eventId;
	}

	public void setEventId(Long eventId) {
		this.eventId = eventId;
	}

	@Column(name = "ACTION_TYPE_ID")
	public Long getActionTypeId() {
		return this.actionTypeId;
	}

	public void setActionTypeId(Long actionTypeId) {
		this.actionTypeId = actionTypeId;
	}

	@Column(name = "ACTION_TYPE_INDEX")
	public Long getActionTypeIndex() {
		return actionTypeIndex;
	}

	public void setActionTypeIndex(Long actionTypeIndex) {
		this.actionTypeIndex = actionTypeIndex;
	}
	

}
