package com.viettel.ocs.entity;
// Generated Sep 2, 2016 4:54:08 PM by Hibernate Tools 3.2.1.GA


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Transient;

/**
 * EventActionMap generated by hbm2java
 */
@Entity
@Table(name="event_action_map"
)
public class EventActionMap extends BaseEntity  implements java.io.Serializable {

	@Override
	@Transient
	public String getNodeName() {
		return null;
	}
	private Long domainId;
	@Column(name="DOMAIN_ID")
    public Long getDomainId() {
		return domainId;
	}
	public void setDomainId(Long domainId) {
		this.domainId = domainId;
	}
     private long eventActionMapId;
     private Long eventId;
     private Long actionId;

    public EventActionMap() {
    }

    public EventActionMap(Long eventId, Long actionId) {
       this.eventId = eventId;
       this.actionId = actionId;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)
    
    @Column(name="EVENT_ACTION_MAP_ID", unique=true, nullable=false)
    public long getEventActionMapId() {
        return this.eventActionMapId;
    }
    
    public void setEventActionMapId(long eventActionMapId) {
        this.eventActionMapId = eventActionMapId;
    }
    
    @Column(name="EVENT_ID")
    public Long getEventId() {
        return this.eventId;
    }
    
    public void setEventId(Long eventId) {
        this.eventId = eventId;
    }
    
    @Column(name="ACTION_ID")
    public Long getActionId() {
        return this.actionId;
    }
    
    public void setActionId(Long actionId) {
        this.actionId = actionId;
    }




}


