package com.viettel.ocs.entity;
// Generated Sep 2, 2016 4:54:08 PM by Hibernate Tools 3.2.1.GA

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Transient;

/**
 * Formula generated by hbm2java
 */
@Entity
@Table(name = "formula")
public class Formula extends BaseEntity implements java.io.Serializable, Cloneable {

	@Override
	@Transient
	public String getNodeName() {
		return null;
	}

	private Long domainId;

	@Column(name = "DOMAIN_ID")
	public Long getDomainId() {
		return domainId;
	}

	public void setDomainId(Long domainId) {
		this.domainId = domainId;
	}

	private long formulaId;
	private Long formulaType;
	private Long a;
	private Long b;
	private Long per;
	private Long categoryId;
	private Long triggerOcsId;
	private Boolean isPercentage = false;
	private Long templateBits = 0L;
	private Long normalizingValueType;
	private Long formulaErrorCode;
	private Boolean isSendRar;
	private Boolean isMonitor;
	private Long reservationTime;
	private String triggerIds;
	private String statisticItems;

	public Formula() {
	}

	public Formula(Long formulaType, Long a, Long b, Long per, Long categoryId, Long triggerOcsId, Boolean isPercentage,
			Long templateBits, Long normalizingValueType, Long formulaErrorCode, Boolean isSendRar, Boolean isMonitor,
			Long reservationTime, String triggerIds, String statisticItems) {
		this.formulaType = formulaType;
		this.a = a;
		this.b = b;
		this.per = per;
		this.categoryId = categoryId;
		this.triggerOcsId = triggerOcsId;
		this.isPercentage = isPercentage;
		this.templateBits = templateBits;
		this.normalizingValueType = normalizingValueType;
		this.formulaErrorCode = formulaErrorCode;
		this.isSendRar = isSendRar;
		this.isMonitor = isMonitor;
		this.reservationTime = reservationTime;
		this.triggerIds = triggerIds;
		this.statisticItems = statisticItems;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "FORMULA_ID", unique = true, nullable = false)
	public long getFormulaId() {
		return this.formulaId;
	}

	public void setFormulaId(long formulaId) {
		this.formulaId = formulaId;
	}

	@Column(name = "FORMULA_TYPE")
	public Long getFormulaType() {
		return this.formulaType;
	}

	public void setFormulaType(Long formulaType) {
		this.formulaType = formulaType;
	}

	@Column(name = "A")
	public Long getA() {
		return this.a;
	}

	public void setA(Long a) {
		this.a = a;
	}

	@Column(name = "B")
	public Long getB() {
		return this.b;
	}

	public void setB(Long b) {
		this.b = b;
	}

	@Column(name = "PER")
	public Long getPer() {
		return this.per;
	}

	public void setPer(Long per) {
		this.per = per;
	}

	@Column(name = "CATEGORY_ID")
	public Long getCategoryId() {
		return this.categoryId;
	}

	public void setCategoryId(Long categoryId) {
		this.categoryId = categoryId;
	}

	@Column(name = "TRIGGER_OCS_ID")
	public Long getTriggerOcsId() {
		return this.triggerOcsId;
	}

	public void setTriggerOcsId(Long triggerOcsId) {
		this.triggerOcsId = triggerOcsId;
	}

	@Column(name = "IS_PERCENTAGE")
	public Boolean getIsPercentage() {
		return this.isPercentage;
	}

	public void setIsPercentage(Boolean isPercentage) {
		this.isPercentage = isPercentage;
	}

	@Column(name = "TEMPLATE_BITS")
	public Long getTemplateBits() {
		return this.templateBits;
	}

	public void setTemplateBits(Long templateBits) {
		this.templateBits = templateBits;
	}

	@Column(name = "NORMALIZING_VALUE_TYPE")
	public Long getNormalizingValueType() {
		return this.normalizingValueType;
	}

	public void setNormalizingValueType(Long normalizingValueType) {
		this.normalizingValueType = normalizingValueType;
	}

	@Column(name = "FORMULA_ERROR_CODE")
	public Long getFormulaErrorCode() {
		return this.formulaErrorCode;
	}

	public void setFormulaErrorCode(Long formulaErrorCode) {
		this.formulaErrorCode = formulaErrorCode;
	}

	@Column(name = "IS_SEND_RAR")
	public Boolean getIsSendRar() {
		return this.isSendRar;
	}

	public void setIsSendRar(Boolean isSendRar) {
		this.isSendRar = isSendRar;
	}

	@Column(name = "IS_MONITOR")
	public Boolean getIsMonitor() {
		return this.isMonitor;
	}

	public void setIsMonitor(Boolean isMonitor) {
		this.isMonitor = isMonitor;
	}

	@Column(name = "RESERVATION_TIME")
	public Long getReservationTime() {
		return this.reservationTime;
	}

	public void setReservationTime(Long reservationTime) {
		this.reservationTime = reservationTime;
	}

	@Column(name = "TRIGGER_IDS", length = 50)
	public String getTriggerIds() {
		return this.triggerIds;
	}

	public void setTriggerIds(String triggerIds) {
		this.triggerIds = triggerIds;
	}
	
	@Column(name = "STATISTIC_ITEMS")
	public String getStatisticItems() {
		return statisticItems;
	}

	public void setStatisticItems(String statisticItems) {
		this.statisticItems = statisticItems;
	}

	@Override
	public Formula clone() throws CloneNotSupportedException {
		return (Formula) super.clone();
	}

}
