package com.viettel.ocs.entity;
// Generated Sep 2, 2016 4:54:08 PM by Hibernate Tools 3.2.1.GA


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Transient;

/**
 * GeoHomeZone generated by hbm2java
 */
@Entity
@Table(name="geo_home_zone"
)
public class GeoHomeZone extends BaseEntity  implements java.io.Serializable, Cloneable {

	@Override
	@Transient
	public String getNodeName() {
		return this.geoHomeZoneName;
	}
	private Long domainId;
	@Column(name="DOMAIN_ID")
    public Long getDomainId() {
		return domainId;
	}
	public void setDomainId(Long domainId) {
		this.domainId = domainId;
	}
     private long geoHomeZoneId;
     private String geoHomeZoneName;
     private String geoHomeZoneCode;
     private String remark;
     private Long geoHomeZoneType;
     private Long categoryId;
     private Long index;

    public GeoHomeZone() {
    }

    public GeoHomeZone(String geoHomeZoneName, String geoHomeZoneCode, String remark, Long geoHomeZoneType, Long categoryId, Long index) {
       this.geoHomeZoneName = geoHomeZoneName;
       this.geoHomeZoneCode = geoHomeZoneCode;
       this.remark = remark;
       this.geoHomeZoneType = geoHomeZoneType;
       this.categoryId = categoryId;
       this.index = index;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)
    
    @Column(name="GEO_HOME_ZONE_ID", unique=true, nullable=false)
    public long getGeoHomeZoneId() {
        return this.geoHomeZoneId;
    }
    
    public void setGeoHomeZoneId(long geoHomeZoneId) {
        this.geoHomeZoneId = geoHomeZoneId;
    }
    
    @Column(name="GEO_HOME_ZONE_NAME", length=50)
    public String getGeoHomeZoneName() {
        return this.geoHomeZoneName;
    }
    
    public void setGeoHomeZoneName(String geoHomeZoneName) {
        this.geoHomeZoneName = geoHomeZoneName;
    }
    
    @Column(name="GEO_HOME_ZONE_CODE", length=50)
    public String getGeoHomeZoneCode() {
        return this.geoHomeZoneCode;
    }
    
    public void setGeoHomeZoneCode(String geoHomeZoneCode) {
        this.geoHomeZoneCode = geoHomeZoneCode;
    }
    
    @Column(name="REMARK", length=250)
    public String getRemark() {
        return this.remark;
    }
    
    public void setRemark(String remark) {
        this.remark = remark;
    }
    
    @Column(name="GEO_HOME_ZONE_TYPE")
    public Long getGeoHomeZoneType() {
        return this.geoHomeZoneType;
    }
    
    public void setGeoHomeZoneType(Long geoHomeZoneType) {
        this.geoHomeZoneType = geoHomeZoneType;
    }
    
    @Column(name="CATEGORY_ID")
    public Long getCategoryId() {
        return this.categoryId;
    }
    
    public void setCategoryId(Long categoryId) {
        this.categoryId = categoryId;
    }
    
	@Column(name = "POS_INDEX", length = 20)
	public Long getIndex() {
		return index;
	}

	public void setIndex(Long index) {
		this.index = index;
	}
	@Override
	public GeoHomeZone clone() throws CloneNotSupportedException {
		// TODO Auto-generated method stub
		return (GeoHomeZone) super.clone();
	}

    



}


