package com.viettel.ocs.entity;
// Generated Sep 2, 2016 4:54:08 PM by Hibernate Tools 3.2.1.GA


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.Transient;

/**
 * GeoNetZone generated by hbm2java
 */
@Entity
@Table(name="geo_net_zone"
)
public class GeoNetZone extends BaseEntity  implements java.io.Serializable {

	@Override
	@Transient
	public String getNodeName() {
		return cellId.toString();
	}
	private Long domainId;
	@Column(name="DOMAIN_ID")
    public Long getDomainId() {
		return domainId;
	}
	public void setDomainId(Long domainId) {
		this.domainId = domainId;
	}
     private long geoNetZoneId;
     private Long cellId;
     private Long geoHomeZoneId;
     private Date updateDate;

    public GeoNetZone() {
    }

    public GeoNetZone(Long cellId, Long geoHomeZoneId, Date updateDate) {
       this.cellId = cellId;
       this.geoHomeZoneId = geoHomeZoneId;
       this.updateDate = updateDate;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)
    
    @Column(name="GEO_NET_ZONE_ID", unique=true, nullable=false)
    public long getGeoNetZoneId() {
        return this.geoNetZoneId;
    }
    
    public void setGeoNetZoneId(long geoNetZoneId) {
        this.geoNetZoneId = geoNetZoneId;
    }
    
    @Column(name="CELL_ID")
    public Long getCellId() {
        return this.cellId;
    }
    
    public void setCellId(Long cellId) {
        this.cellId = cellId;
    }
    
    @Column(name="GEO_HOME_ZONE_ID")
    public Long getGeoHomeZoneId() {
        return this.geoHomeZoneId;
    }
    
    public void setGeoHomeZoneId(Long geoHomeZoneId) {
        this.geoHomeZoneId = geoHomeZoneId;
    }
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="UPDATE_DATE", length=19)
    public Date getUpdateDate() {
        return this.updateDate;
    }
    
    public void setUpdateDate(Date updateDate) {
        this.updateDate = updateDate;
    }




}


