package com.viettel.ocs.entity;
// Generated Sep 2, 2016 4:54:08 PM by Hibernate Tools 3.2.1.GA


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Transient;

/**
 * Lang generated by hbm2java
 */
@Entity
@Table(name="lang"
)
public class Lang extends BaseEntity  implements java.io.Serializable {

	@Override
	@Transient
	public String getNodeName() {
		return null;
	}
	
     private long langId;
     private String langCode;
     private String nationality;
     private String langName;

    public Lang() {
    }

    public Lang(String langCode, String nationality) {
       this.langCode = langCode;
       this.nationality = nationality;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)
    
    @Column(name="LANG_ID", unique=true, nullable=false)
    public long getLangId() {
        return this.langId;
    }
    
    public void setLangId(long langId) {
        this.langId = langId;
    }
    
    @Column(name="LANG_CODE", length=30)
    public String getLangCode() {
        return this.langCode;
    }
    
    public void setLangCode(String langCode) {
        this.langCode = langCode;
    }
    
    @Column(name="LANG_NAME", length=30)
    public String getLangName() {
		return langName;
	}

	public void setLangName(String langName) {
		this.langName = langName;
	}

	@Column(name="NATIONALITY", length=100)
    public String getNationality() {
        return this.nationality;
    }
    
    public void setNationality(String nationality) {
        this.nationality = nationality;
    }




}


