package com.viettel.ocs.entity;
// Generated Sep 2, 2016 4:54:08 PM by Hibernate Tools 3.2.1.GA


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Transient;

/**
 * MapAcmbalBal generated by hbm2java
 */
@Entity
@Table(name="map_acmbal_bal"
)
public class MapAcmbalBal extends BaseEntity  implements java.io.Serializable, Cloneable {

	@Override
	@Transient
	public String getNodeName() {
		return this.name;
	}
	private Long domainId;
	@Column(name="DOMAIN_ID")
    public Long getDomainId() {
		return domainId;
	}
	public void setDomainId(Long domainId) {
		this.domainId = domainId;
	}
     private long mapAcmBaltypeId;
     private Long acmBaltypeId;
     private Long baltypeId;
     private String name;
     private String remark;
     private Long categoryId;
     private Long index;

    public MapAcmbalBal() {
    }

	public MapAcmbalBal(long mapAcmBaltypeId, Long acmBaltypeId, Long baltypeId, String name, String remark,
			Long categoryId,Long index) {
		super();
		this.mapAcmBaltypeId = mapAcmBaltypeId;
		this.acmBaltypeId = acmBaltypeId;
		this.baltypeId = baltypeId;
		this.name = name;
		this.remark = remark;
		this.categoryId = categoryId;
		this.index = index;
	}
	@Id @GeneratedValue(strategy=IDENTITY)
    
    @Column(name="MAP_ACM_BALTYPE_ID", unique=true, nullable=false)
    public long getMapAcmBaltypeId() {
        return this.mapAcmBaltypeId;
    }
    
    public void setMapAcmBaltypeId(long mapAcmBaltypeId) {
        this.mapAcmBaltypeId = mapAcmBaltypeId;
    }
    
    @Column(name="ACM_BALTYPE_ID")
    public Long getAcmBaltypeId() {
        return this.acmBaltypeId;
    }
    
    public void setAcmBaltypeId(Long acmBaltypeId) {
        this.acmBaltypeId = acmBaltypeId;
    }
    
    @Column(name="BALTYPE_ID")
    public Long getBaltypeId() {
        return this.baltypeId;
    }
    
    public void setBaltypeId(Long baltypeId) {
        this.baltypeId = baltypeId;
    }
    
    @Column(name="NAME")
	public String getName() {
		return name;
	}
	public void setName(String name) {
		this.name = name;
	}
	
	@Column(name="REMARK")
	public String getRemark() {
		return remark;
	}
	public void setRemark(String remark) {
		this.remark = remark;
	}
	
	@Column(name = "CATEGORY_ID")
	public Long getCategoryId() {
		return this.categoryId;
	}

	public void setCategoryId(Long categoryId) {
		this.categoryId = categoryId;
	}
	
	@Column(name = "POS_INDEX", length = 20)
	public Long getIndex() {
		return index;
	}

	public void setIndex(Long index) {
		this.index = index;
	}
	@Override
	public MapAcmbalBal clone() throws CloneNotSupportedException {
		// TODO Auto-generated method stub
		return (MapAcmbalBal) super.clone();
	}
	
	

}


