package com.viettel.ocs.entity;
// Generated Sep 2, 2016 4:54:08 PM by Hibernate Tools 3.2.1.GA

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Transient;

/**
 * MapSharebalBal generated by hbm2java
 */
@Entity
@Table(name = "map_sharebal_bal")
public class MapSharebalBal extends BaseEntity implements java.io.Serializable, Cloneable {

	@Override
	@Transient
	public String getNodeName() {
		return this.name;
	}
	
	private Long domainId;

	@Column(name = "DOMAIN_ID")
	public Long getDomainId() {
		return domainId;
	}

	public void setDomainId(Long domainId) {
		this.domainId = domainId;
	}

	private long mapSharebalBalId;
	private Long shareType;
	private Long baltypeId;
	private String name;
	private String remark;
	private Long categoryId;
	private Long sharebalTypeId;
	private Long index;

	public MapSharebalBal() {
	}

	public MapSharebalBal(long mapSharebalBalId, Long shareType, Long baltypeId, String name, String remark,
			Long categoryId, Long sharebalTypeId,Long index) {
		super();
		this.mapSharebalBalId = mapSharebalBalId;
		this.shareType = shareType;
		this.baltypeId = baltypeId;
		this.name = name;
		this.remark = remark;
		this.categoryId = categoryId;
		this.sharebalTypeId = sharebalTypeId;
		this.index = index;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "MAP_SHAREBAL_BAL_ID", unique = true, nullable = false)
	public long getMapSharebalBalId() {
		return this.mapSharebalBalId;
	}

	public void setMapSharebalBalId(long mapSharebalBalId) {
		this.mapSharebalBalId = mapSharebalBalId;
	}

	@Column(name = "SHARE_TYPE")
	public Long getShareType() {
		return shareType;
	}

	public void setShareType(Long shareType) {
		this.shareType = shareType;
	}



	@Column(name = "BALTYPE_ID")
	public Long getBaltypeId() {
		return this.baltypeId;
	}

	public void setBaltypeId(Long baltypeId) {
		this.baltypeId = baltypeId;
	}

	@Column(name = "NAME")
	public String getName() {
		return name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "REMARK")
	public String getRemark() {
		return remark;
	}

	public void setRemark(String remark) {
		this.remark = remark;
	}

	@Column(name = "CATEGORY_ID")
	public Long getCategoryId() {
		return this.categoryId;
	}

	public void setCategoryId(Long categoryId) {
		this.categoryId = categoryId;
	}

	
	@Column(name = "SHARE_BALTYPE_ID")
	public Long getSharebalTypeId() {
		return sharebalTypeId;
	}

	public void setSharebalTypeId(Long sharebalTypeId) {
		this.sharebalTypeId = sharebalTypeId;
	}
	
	@Column(name = "POS_INDEX", length = 20)
	public Long getIndex() {
		return index;
	}

	public void setIndex(Long index) {
		this.index = index;
	}

	@Override
	public MapSharebalBal clone() throws CloneNotSupportedException {
		// TODO Auto-generated method stub
		return (MapSharebalBal) super.clone();
	}

}
