package com.viettel.ocs.entity;

import static javax.persistence.GenerationType.IDENTITY;

import java.io.Serializable;

// Generated Sep 2, 2016 4:54:08 PM by Hibernate Tools 3.2.1.GA

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Transient;

/**
 * MonitorKey generated by hbm2java
 */
@Entity
@Table(name = "monitor_key")
public class MonitorKey extends BaseEntity implements Serializable,Cloneable{

	@Override
	@Transient
	public String getNodeName() {
		return remark;
	}

	private Long domainId;

	private long monitorKeyId;
	private Long monitorKey;
	private String remark;

	public MonitorKey() {
	}

	public MonitorKey(Long monitorKey) {
		this.monitorKey = monitorKey;
	}

	public MonitorKey(Long monitorKey, String remark) {
		this.monitorKey = monitorKey;
		this.remark = remark;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "MONITOR_KEY_ID", unique = true, nullable = false)
	public long getMonitorKeyId() {
		return this.monitorKeyId;
	}

	public void setMonitorKeyId(long monitorKeyId) {
		this.monitorKeyId = monitorKeyId;
	}

	@Column(name = "MONITOR_KEY", nullable = false)
	public Long getMonitorKey() {
		return this.monitorKey;
	}

	public void setMonitorKey(Long monitorKey) {
		this.monitorKey = monitorKey;
	}

	@Column(name = "REMARK", length = 100)
	public String getRemark() {
		return this.remark;
	}

	public void setRemark(String remark) {
		this.remark = remark;
	}

	@Column(name = "DOMAIN_ID")
	public Long getDomainId() {
		return domainId;
	}

	public void setDomainId(Long domainId) {
		this.domainId = domainId;
	}

	@Override
	public MonitorKey clone() throws CloneNotSupportedException {
		return (MonitorKey) super.clone();
	}
}
