package com.viettel.ocs.entity;
// Generated Sep 2, 2016 4:54:08 PM by Hibernate Tools 3.2.1.GA


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Transient;

/**
 * NomalizerNormParamMap generated by hbm2java
 */
@Entity
@Table(name="nomalizer_norm_param_map"
)
public class NomalizerNormParamMap extends BaseEntity  implements java.io.Serializable {

	@Override
	@Transient
	public String getNodeName() {
		return null;
	}
	private Long domainId;
	@Column(name="DOMAIN_ID")
    public Long getDomainId() {
		return domainId;
	}
	public void setDomainId(Long domainId) {
		this.domainId = domainId;
	}
     private long nomalizerNormParamMapId;
     private Long normalizerId;
     private Long normParamId;

    public NomalizerNormParamMap() {
    }

    public NomalizerNormParamMap(Long normalizerId, Long normParamId) {
       this.normalizerId = normalizerId;
       this.normParamId = normParamId;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)
    
    @Column(name="NOMALIZER_NORM_PARAM_MAP_ID", unique=true, nullable=false)
    public long getNomalizerNormParamMapId() {
        return this.nomalizerNormParamMapId;
    }
    
    public void setNomalizerNormParamMapId(long nomalizerNormParamMapId) {
        this.nomalizerNormParamMapId = nomalizerNormParamMapId;
    }
    
    @Column(name="NORMALIZER_ID")
    public Long getNormalizerId() {
        return this.normalizerId;
    }
    
    public void setNormalizerId(Long normalizerId) {
        this.normalizerId = normalizerId;
    }
    
    @Column(name="NORM_PARAM_ID")
    public Long getNormParamId() {
        return this.normParamId;
    }
    
    public void setNormParamId(Long normParamId) {
        this.normParamId = normParamId;
    }




}


