package com.viettel.ocs.entity;
// Generated Sep 2, 2016 4:54:08 PM by Hibernate Tools 3.2.1.GA

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Transient;

/**
 * NormParam generated by hbm2java
 */
@Entity
@Table(name = "norm_param")
public class NormParam extends BaseEntity implements java.io.Serializable, Cloneable {

	@Override
	@Transient
	public String getNodeName() {
		return null;
	}

	private Long domainId;

	@Column(name = "DOMAIN_ID")
	public Long getDomainId() {
		return domainId;
	}

	public void setDomainId(Long domainId) {
		this.domainId = domainId;
	}

	private long normParamId;
	private String configInput;
	private Long normParamIndex;

	public NormParam() {
	}

	public NormParam(String configInput, Long normParamIndex) {
		this.configInput = configInput;
		this.normParamIndex = normParamIndex;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "NORM_PARAM_ID", unique = true, nullable = false)
	public long getNormParamId() {
		return this.normParamId;
	}

	public void setNormParamId(long normParamId) {
		this.normParamId = normParamId;
	}

	@Column(name = "CONFIG_INPUT", length = 65535)
	public String getConfigInput() {
		return this.configInput;
	}

	public void setConfigInput(String configInput) {
		this.configInput = configInput;
	}

	@Column(name = "NORM_PARAM_INDEX")
	public Long getNormParamIndex() {
		return this.normParamIndex;
	}

	public void setNormParamIndex(Long normParamIndex) {
		this.normParamIndex = normParamIndex;
	}

	@Override
	public NormParam clone() throws CloneNotSupportedException {
		return (NormParam) super.clone();
	}

}
