package com.viettel.ocs.entity;
// Generated Sep 2, 2016 4:54:08 PM by Hibernate Tools 3.2.1.GA

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Transient;

/**
 * OfferPackage generated by hbm2java
 */
@Entity
@Table(name = "offer_package")
public class OfferPackage extends BaseEntity implements java.io.Serializable, Cloneable {

	@Override
	@Transient
	public String getNodeName() {
		return offerPkgName;
	}

	private Long domainId;

	@Column(name = "DOMAIN_ID")
	public Long getDomainId() {
		return domainId;
	}

	public void setDomainId(Long domainId) {
		this.domainId = domainId;
	}

	private long offerPkgId;
	private String offerPkgName;
	private Long categoryId;
	private String externalId;
	private String remark;
	private Long status;
	private Long mainOfferId;
	private Long commonOfferId;
	private Long index;
	private Long offerPkgType;

	public OfferPackage() {
	}

	public OfferPackage(String offerPkgName, Long categoryId, String externalId, String remark, Long status,
			Long mainOfferId, Long commonOfferId) {
		this.offerPkgName = offerPkgName;
		this.categoryId = categoryId;
		this.externalId = externalId;
		this.remark = remark;
		this.status = status;
		this.mainOfferId = mainOfferId;
		this.commonOfferId = commonOfferId;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "OFFER_PKG_ID", unique = true, nullable = false)
	public long getOfferPkgId() {
		return this.offerPkgId;
	}

	public void setOfferPkgId(long offerPkgId) {
		this.offerPkgId = offerPkgId;
	}

	@Column(name = "OFFER_PKG_NAME", length = 65535)
	public String getOfferPkgName() {
		return this.offerPkgName;
	}

	public void setOfferPkgName(String offerPkgName) {
		this.offerPkgName = offerPkgName;
	}

	@Column(name = "OFFER_PKG_TYPE")
	public Long getOfferPkgType() {
		return offerPkgType;
	}

	public void setOfferPkgType(Long offerPkgType) {
		this.offerPkgType = offerPkgType;
	}

	@Column(name = "CATEGORY_ID")
	public Long getCategoryId() {
		return this.categoryId;
	}

	public void setCategoryId(Long categoryId) {
		this.categoryId = categoryId;
	}

	@Column(name = "EXTERNAL_ID", length = 65535)
	public String getExternalId() {
		return this.externalId;
	}

	public void setExternalId(String externalId) {
		this.externalId = externalId;
	}

	@Column(name = "REMARK", length = 65535)
	public String getRemark() {
		return this.remark;
	}

	public void setRemark(String remark) {
		this.remark = remark;
	}

	@Column(name = "STATUS")
	public Long getStatus() {
		return this.status;
	}

	public void setStatus(Long status) {
		this.status = status;
	}

	@Column(name = "MAIN_OFFER_ID")
	public Long getMainOfferId() {
		return this.mainOfferId;
	}

	public void setMainOfferId(Long mainOfferId) {
		this.mainOfferId = mainOfferId;
	}

	@Column(name = "COMMON_OFFER_ID")
	public Long getCommonOfferId() {
		return this.commonOfferId;
	}

	public void setCommonOfferId(Long commonOfferId) {
		this.commonOfferId = commonOfferId;
	}

	@Column(name = "POS_INDEX")
	public Long getIndex() {
		return index;
	}

	public void setIndex(Long index) {
		this.index = index;
	}

	@Override
	public OfferPackage clone() throws CloneNotSupportedException {
		return (OfferPackage) super.clone();
	}

}
