package com.viettel.ocs.entity;
// Generated Sep 2, 2016 4:54:08 PM by Hibernate Tools 3.2.1.GA

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Transient;

/**
 * OfferpkgOfferMap generated by hbm2java
 */
@Entity
@Table(name = "offerpkg_offer_map")
public class OfferpkgOfferMap extends BaseEntity implements java.io.Serializable, Cloneable {

	@Override
	@Transient
	public String getNodeName() {
		return null;
	}

	private Long domainId;

	@Column(name = "DOMAIN_ID")
	public Long getDomainId() {
		return domainId;
	}

	public void setDomainId(Long domainId) {
		this.domainId = domainId;
	}

	private long offerpkgOfferMapId;
	private Long offerId;
	private Long offerPackageId;
	private Boolean addOn;
	private Boolean exchangeable;
	private Integer index;;

	public OfferpkgOfferMap() {
	}

	public OfferpkgOfferMap(Long offerId, Long offerPackageId, Boolean addOn, Boolean exchangeable) {
		super();
		this.offerId = offerId;
		this.offerPackageId = offerPackageId;
		this.addOn = addOn;
		this.exchangeable = exchangeable;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "OFFERPKG_OFFER_MAP_ID", unique = true, nullable = false)
	public long getOfferpkgOfferMapId() {
		return this.offerpkgOfferMapId;
	}

	public void setOfferpkgOfferMapId(long offerpkgOfferMapId) {
		this.offerpkgOfferMapId = offerpkgOfferMapId;
	}

	@Column(name = "OFFER_PACKAGE_ID")
	public Long getOfferPackageId() {
		return this.offerPackageId;
	}

	public void setOfferPackageId(Long offerPackageId) {
		this.offerPackageId = offerPackageId;
	}

	@Column(name = "ADD_ON")
	public Boolean getAddOn() {
		return this.addOn;
	}

	public void setAddOn(Boolean addOn) {
		this.addOn = addOn;
	}

	@Column(name = "EXCHANGEABLE")
	public Boolean getExchangeable() {
		return this.exchangeable;
	}

	public void setExchangeable(Boolean exchangeable) {
		this.exchangeable = exchangeable;
	}

	@Column(name = "OFFER_ID")
	public long getOfferId() {
		return this.offerId;
	}

	public void setOfferId(long offerId) {
		this.offerId = offerId;
	}

	@Column(name = "POS_INDEX")
	public Integer getIndex() {
		return index;
	}

	public void setIndex(Integer index) {
		this.index = index;
	}

	@Override
	public OfferpkgOfferMap clone() throws CloneNotSupportedException {
		return (OfferpkgOfferMap) super.clone();
	}

}
