package com.viettel.ocs.entity;
// Generated Sep 2, 2016 4:54:08 PM by Hibernate Tools 3.2.1.GA


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Transient;

/**
 * OfferActionMap generated by hbm2java
 */
@Entity
@Table(name="offer_action_map"
)
public class OfferActionMap extends BaseEntity  implements java.io.Serializable {

	@Override
	@Transient
	public String getNodeName() {
		return null;
	}
	private Long domainId;
	@Column(name="DOMAIN_ID")
    public Long getDomainId() {
		return domainId;
	}
	public void setDomainId(Long domainId) {
		this.domainId = domainId;
	}
     private long offerActionMapId;
     private Long offerId;
     private Long actionId;
     private Long mapIndex;

    public OfferActionMap() {
    }
    
    public OfferActionMap(Long offerId, Long actionId) {
        this.offerId = offerId;
        this.actionId = actionId;
     }

    public OfferActionMap(Long offerId, Long actionId, Long mapIndex) {
       this.offerId = offerId;
       this.actionId = actionId;
       this.mapIndex = mapIndex;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)
    
    @Column(name="OFFER_ACTION_MAP_ID", unique=true, nullable=false)
    public long getOfferActionMapId() {
        return this.offerActionMapId;
    }
    
    public void setOfferActionMapId(long offerActionMapId) {
        this.offerActionMapId = offerActionMapId;
    }
    
    @Column(name="OFFER_ID")
    public Long getOfferId() {
        return this.offerId;
    }
    
    public void setOfferId(Long offerId) {
        this.offerId = offerId;
    }
    
    @Column(name="ACTION_ID")
    public Long getActionId() {
        return this.actionId;
    }
    
    public void setActionId(Long actionId) {
        this.actionId = actionId;
    }
    
    @Column(name="MAP_INDEX")
    public Long getMapIndex() {
        return this.mapIndex;
    }
    
    public void setMapIndex(Long mapIndex) {
        this.mapIndex = mapIndex;
    }




}


