package com.viettel.ocs.entity;
// Generated Sep 2, 2016 4:54:08 PM by Hibernate Tools 3.2.1.GA

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.Transient;

import com.viettel.ocs.constant.ContantsUtil;

/**
 * Offer generated by hbm2java
 */
@Entity
@Table(name = "offer")
public class Offer extends BaseEntity implements java.io.Serializable, Cloneable {

	@Override
	@Transient
	public String getNodeName() {

		if (this.offerName != null && !this.offerName.isEmpty()) {
			if (isVersionName()) {
				if(offerUsage > 0) {
					return this.offerName + " - Version-" + this.versionInfo + "(" + offerUsage + ")";	
				} else {
					return this.offerName + " - Version-" + this.versionInfo;
				}				
			} else
				if(offerUsage > 0) {
					return "Version-" + this.versionInfo + "(" + offerUsage + ")";
				} else {
					return "Version-" + this.versionInfo;	
				}				
		} else {
			return "";
		}
	}

	@Transient
	private boolean versionName;

	@Transient
	public boolean isVersionName() {
		return versionName;
	}

	public void setVersionName(boolean versionName) {
		this.versionName = versionName;
	}
	
	@Transient
	private long offerUsage;

	@Transient
	public long getOfferUsage() {
		return offerUsage;
	}

	public void setOfferUsage(long offerUsage) {
		this.offerUsage = offerUsage;
	}

	private Long domainId;

	@Column(name = "DOMAIN_ID")
	public Long getDomainId() {
		return domainId;
	}

	public void setDomainId(Long domainId) {
		this.domainId = domainId;
	}

	private long offerId;
	private String offerName;
	private Long categoryId;
	private Long priority;
	private Date effDate;
	private Date expDate = new Date(4133869200000L);
	private Long createType;
	private Long offerType;
	private Long billingCycleTypeId;
	private String offerExternalId;
	private String versionInfo = "";
	private Long specialCalMethod;
	private Long offerTemplateId;
	private String description;
	private Long state;
	private Long paymentType = ContantsUtil.PaymentType.PAYMENT_TYPE_PREPAID;
	private String offerCode;
	private Long offerDowngradeId;
	private Long offerUpgradeId;
	private Long offerPackageId;
	private Boolean expirable;
	private Boolean suspendable;

	public Offer() {
	}

	public Offer(String offerName, Long categoryId, Long priority, Date effDate, Date expDate, Long createType,
			Long offerType, Long billingCycleTypeId, String offerExternalId, String versionInfo, Long specialCalMethod,
			Long offerTemplateId, String description, Long state, Long paymentType, String offerCode,
			Long offerDowngradeId, Long offerUpgradeId, Long offerPackageId, Boolean expirable) {
		this.offerName = offerName;
		this.categoryId = categoryId;
		this.priority = priority;
		this.effDate = effDate;
		this.expDate = expDate;
		this.createType = createType;
		this.offerType = offerType;
		this.billingCycleTypeId = billingCycleTypeId;
		this.offerExternalId = offerExternalId;
		this.versionInfo = versionInfo;
		this.specialCalMethod = specialCalMethod;
		this.offerTemplateId = offerTemplateId;
		this.description = description;
		this.state = state;
		this.paymentType = paymentType;
		this.offerCode = offerCode;
		this.offerDowngradeId = offerDowngradeId;
		this.offerUpgradeId = offerUpgradeId;
		this.offerPackageId = offerPackageId;
		this.expirable = expirable;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "OFFER_ID", unique = true, nullable = false)
	public long getOfferId() {
		return this.offerId;
	}

	public void setOfferId(long offerId) {
		this.offerId = offerId;
	}

	@Column(name = "OFFER_NAME", length = 65535)
	public String getOfferName() {
		return this.offerName;
	}

	public void setOfferName(String offerName) {
		this.offerName = offerName;
	}

	@Column(name = "CATEGORY_ID")
	public Long getCategoryId() {
		return this.categoryId;
	}

	public void setCategoryId(Long categoryId) {
		this.categoryId = categoryId;
	}

	@Column(name = "PRIORITY")
	public Long getPriority() {
		return this.priority;
	}

	public void setPriority(Long priority) {
		this.priority = priority;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "EFF_DATE", length = 19)
	public Date getEffDate() {
		return this.effDate;
	}

	public void setEffDate(Date effDate) {
		this.effDate = effDate;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "EXP_DATE", length = 19)
	public Date getExpDate() {
		return this.expDate;
	}

	public void setExpDate(Date expDate) {
		this.expDate = expDate;
	}

	@Column(name = "CREATE_TYPE")
	public Long getCreateType() {
		return this.createType;
	}

	public void setCreateType(Long createType) {
		this.createType = createType;
	}

	@Column(name = "OFFER_TYPE")
	public Long getOfferType() {
		return this.offerType;
	}

	public void setOfferType(Long offerType) {
		this.offerType = offerType;
	}

	@Column(name = "BILLING_CYCLE_TYPE_ID")
	public Long getBillingCycleTypeId() {
		return this.billingCycleTypeId;
	}

	public void setBillingCycleTypeId(Long billingCycleTypeId) {
		this.billingCycleTypeId = billingCycleTypeId;
	}

	@Column(name = "OFFER_EXTERNAL_ID", length = 65535)
	public String getOfferExternalId() {
		return this.offerExternalId;
	}

	public void setOfferExternalId(String offerExternalId) {
		this.offerExternalId = offerExternalId;
	}

	@Column(name = "VERSION_INFO", length = 65535)
	public String getVersionInfo() {
		return this.versionInfo;
	}

	public void setVersionInfo(String versionInfo) {
		this.versionInfo = versionInfo;
	}

	@Column(name = "SPECIAL_CAL_METHOD")
	public Long getSpecialCalMethod() {
		return this.specialCalMethod;
	}

	public void setSpecialCalMethod(Long specialCalMethod) {
		this.specialCalMethod = specialCalMethod;
	}

	@Column(name = "OFFER_TEMPLATE_ID")
	public Long getOfferTemplateId() {
		return this.offerTemplateId;
	}

	public void setOfferTemplateId(Long offerTemplateId) {
		this.offerTemplateId = offerTemplateId;
	}

	@Column(name = "DESCRIPTION", length = 65535)
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@Column(name = "STATE")
	public Long getState() {
		return this.state;
	}

	public void setState(Long state) {
		this.state = state;
	}

	@Column(name = "PAYMENT_TYPE")
	public Long getPaymentType() {
		return this.paymentType;
	}

	public void setPaymentType(Long paymentType) {
		this.paymentType = paymentType;
	}

	@Column(name = "OFFER_CODE", length = 50)
	public String getOfferCode() {
		return this.offerCode;
	}

	public void setOfferCode(String offerCode) {
		this.offerCode = offerCode;
	}

	@Column(name = "OFFER_DOWNGRADE_ID")
	public Long getOfferDowngradeId() {
		return this.offerDowngradeId;
	}

	public void setOfferDowngradeId(Long offerDowngradeId) {
		this.offerDowngradeId = offerDowngradeId;
	}

	@Column(name = "OFFER_UPGRADE_ID")
	public Long getOfferUpgradeId() {
		return this.offerUpgradeId;
	}

	public void setOfferUpgradeId(Long offerUpgradeId) {
		this.offerUpgradeId = offerUpgradeId;
	}

	@Column(name = "OFFER_PACKAGE_ID")
	public Long getOfferPackageId() {
		return this.offerPackageId;
	}

	public void setOfferPackageId(Long offerPackageId) {
		this.offerPackageId = offerPackageId;
	}

	@Column(name = "EXPIRABLE")
	public Boolean getExpirable() {
		return this.expirable;
	}

	public void setExpirable(Boolean expirable) {
		this.expirable = expirable;
	}

	@Column(name = "SUSPENDABLE")
	public Boolean getSuspendable() {
		return suspendable;
	}

	public void setSuspendable(Boolean suspendable) {
		this.suspendable = suspendable;
	}

	/***
	 * So sanh theo CategoryId, Name, ExternalID Phuc vu nhom cac version tren
	 * Tree
	 * 
	 * @param offer
	 * @return
	 */
	public boolean equalWith(Offer offer) {

		if (offer == null)
			return false;

		if (this.getCategoryId() == null || offer.getCategoryId() == null || this.getOfferName() == null
				|| offer.getOfferName() == null || this.getOfferExternalId() == null
				|| offer.getOfferExternalId() == null) {

			return false;
		}

		if (this.getCategoryId().longValue() == offer.getCategoryId().longValue()
				&& this.getOfferName().equals(offer.getOfferName())
				&& this.getOfferExternalId().equals(offer.getOfferExternalId())) {

			return true;
		}

		return false;
	}

	/***
	 * So sanh theo CategoryId, Name, ExternalID Phuc vu nhom cac version tren
	 * Tree
	 * 
	 * @param offerDump
	 * @return
	 */
	public boolean equalWithDump(OfferDump offerDump) {

		if (offerDump == null)
			return false;

		if (this.getCategoryId() == null || offerDump.getCategoryId() == null || this.getOfferName() == null
				|| offerDump.getOfferName() == null || this.getOfferExternalId() == null
				|| offerDump.getOfferExternalId() == null) {

			return false;
		}

		if (this.getCategoryId().longValue() == offerDump.getCategoryId().longValue()
				&& this.getOfferName().equals(offerDump.getOfferName())
				&& this.getOfferExternalId().equals(offerDump.getOfferExternalId())) {

			return true;
		}

		return false;
	}

	@Override
	public Offer clone() throws CloneNotSupportedException {
		return (Offer) super.clone();
	}

}
