package com.viettel.ocs.entity;
// Generated Sep 2, 2016 4:54:08 PM by Hibernate Tools 3.2.1.GA


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Transient;

/**
 * PriceComponentBlockMap generated by hbm2java
 */
@Entity
@Table(name="price_component_block_map"
)
public class PriceComponentBlockMap extends BaseEntity  implements java.io.Serializable {

	@Override
	@Transient
	public String getNodeName() {
		return null;
	}
	private Long domainId;
	@Column(name="DOMAIN_ID")
    public Long getDomainId() {
		return domainId;
	}
	public void setDomainId(Long domainId) {
		this.domainId = domainId;
	}
     private long priceComponentBlockMapId;
     private Long priceComponentId;
     private Long blockId;
     private Long blockIndex;

    public PriceComponentBlockMap() {
    }

    public PriceComponentBlockMap(Long priceComponentId, Long blockId, Long blockIndex) {
       this.priceComponentId = priceComponentId;
       this.blockId = blockId;
       this.blockIndex = blockIndex;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)
    
    @Column(name="PRICE_COMPONENT_BLOCK_MAP_ID", unique=true, nullable=false)
    public long getPriceComponentBlockMapId() {
        return this.priceComponentBlockMapId;
    }
    
    public void setPriceComponentBlockMapId(long priceComponentBlockMapId) {
        this.priceComponentBlockMapId = priceComponentBlockMapId;
    }
    
    @Column(name="PRICE_COMPONENT_ID")
    public Long getPriceComponentId() {
        return this.priceComponentId;
    }
    
    public void setPriceComponentId(Long priceComponentId) {
        this.priceComponentId = priceComponentId;
    }
    
    @Column(name="BLOCK_ID")
    public Long getBlockId() {
        return this.blockId;
    }
    
    public void setBlockId(Long blockId) {
        this.blockId = blockId;
    }
    
    @Column(name="BLOCK_INDEX")
    public Long getBlockIndex() {
        return this.blockIndex;
    }
    
    public void setBlockIndex(Long blockIndex) {
        this.blockIndex = blockIndex;
    }




}


