package com.viettel.ocs.entity;
// Generated Aug 9, 2016 8:58:38 AM by Hibernate Tools 3.2.1.GA

import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Transient;

/**
 * PriceRateMap generated by hbm2java
 */
@Entity
@Table(name="PRICE_RATE_MAP"
    
)
public class PriceRateMap  extends BaseEntity implements java.io.Serializable {


     /**
	 * 
	 */
	private static final long serialVersionUID = -7596870344698081690L;
	private long priceRateMapId;
     private Long priceComponentId;
     private Long rateTableId;

     private Long domainId;
     
     @Column(name="DOMAIN_ID")
    public Long getDomainId() {
		return domainId;
	}

	public void setDomainId(Long domainId) {
		this.domainId = domainId;
	}
 	
    public PriceRateMap() {
    }

	
    public PriceRateMap(long priceRateMapId) {
        this.priceRateMapId = priceRateMapId;
    }
    public PriceRateMap(long priceRateMapId, Long priceComponentId, Long rateTableId) {
       this.priceRateMapId = priceRateMapId;
       this.priceComponentId = priceComponentId;
       this.rateTableId = rateTableId;
    }
   
     @Id @GeneratedValue(strategy=GenerationType.IDENTITY) 
    
    @Column(name="PRICE_RATE_MAP_ID", unique=true, nullable=false, precision=14, scale=0)
    public long getPriceRateMapId() {
        return this.priceRateMapId;
    }
    
    public void setPriceRateMapId(long priceRateMapId) {
        this.priceRateMapId = priceRateMapId;
    }
    
    @Column(name="PRICE_COMPONENT_ID", precision=14, scale=0)
    public Long getPriceComponentId() {
        return this.priceComponentId;
    }
    
    public void setPriceComponentId(Long priceComponentId) {
        this.priceComponentId = priceComponentId;
    }
    
    @Column(name="RATE_TABLE_ID", precision=14, scale=0)
    public Long getRateTableId() {
        return this.rateTableId;
    }
    
    public void setRateTableId(Long rateTableId) {
        this.rateTableId = rateTableId;
    }



	@Override
	@Transient
	public String getNodeName() {
		return null;
	}


}


