package com.viettel.ocs.entity;
// Generated Sep 2, 2016 4:54:08 PM by Hibernate Tools 3.2.1.GA

import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Transient;

/**
 * PriceComponent generated by hbm2java
 */
@Entity
@Table(name = "price_component")
public class PriceComponent extends BaseEntity implements java.io.Serializable, Cloneable {

	@Override
	@Transient
	public String getNodeName() {
		return this.priceComponentName;
	}

	private Long domainId;

	@Column(name = "DOMAIN_ID")
	public Long getDomainId() {
		return domainId;
	}

	public void setDomainId(Long domainId) {
		this.domainId = domainId;
	}

	private long priceComponentId;
	private String priceComponentName;
	private Long categoryId;
	private String remark;
	private Long index;
	private Boolean generated;
	private Long pcType;

	public PriceComponent() {
	}

	public PriceComponent(String priceComponentName, Long categoryId, String remark) {
		this.priceComponentName = priceComponentName;
		this.categoryId = categoryId;
		this.remark = remark;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "PRICE_COMPONENT_ID", unique = true, nullable = false)
	public long getPriceComponentId() {
		return this.priceComponentId;
	}

	public void setPriceComponentId(long priceComponentId) {
		this.priceComponentId = priceComponentId;
	}

	@Column(name = "PRICE_COMPONENT_NAME", length = 65535)
	public String getPriceComponentName() {
		return this.priceComponentName;
	}

	public void setPriceComponentName(String priceComponentName) {
		this.priceComponentName = priceComponentName;
	}

	@Column(name = "CATEGORY_ID")
	public Long getCategoryId() {
		return this.categoryId;
	}

	public void setCategoryId(Long categoryId) {
		this.categoryId = categoryId;
	}

	@Column(name = "REMARK", length = 65535)
	public String getRemark() {
		return this.remark;
	}

	public void setRemark(String remark) {
		this.remark = remark;
	}

	@Column(name = "IS_GENERATED")
	public Boolean isGenerated() {
		return generated;
	}

	public void setGenerated(Boolean generated) {
		this.generated = generated;
	}

	@Override
	public PriceComponent clone() throws CloneNotSupportedException {
		return (PriceComponent) super.clone();
	}

	@Column(name = "POS_INDEX")
	public Long getIndex() {
		return index;
	}

	public void setIndex(Long index) {
		this.index = index;
	}

	@Column(name = "PC_TYPE_ID")
	public Long getPcType() {
		return pcType;
	}

	public void setPcType(Long pcType) {
		this.pcType = pcType;
	}
	
	

}
