package com.viettel.ocs.entity;

// Generated Sep 2, 2016 4:54:08 PM by Hibernate Tools 3.2.1.GA

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;

import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Transient;

/**
 * ProfilePep generated by hbm2java
 */
@Entity
@Table(name = "profile_pep")
public class ProfilePep extends BaseEntity implements java.io.Serializable, Cloneable {

	private long profilePepId;
	private String profilePepName;
	private Long qosId;
	private Long monitorKey;
	private Long priority;
	private Long categoryId;
	private String remark;

	public ProfilePep() {
	}

	public ProfilePep(String profilePepName, Long qosId, Long monitorKey, Long priority, Long categoryID,
			String remark) {
		this.profilePepName = profilePepName;
		this.qosId = qosId;
		this.monitorKey = monitorKey;
		this.priority = priority;
		this.categoryId = categoryID;
		this.remark = remark;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "PROFILE_PEP_ID", unique = true, nullable = false)
	public long getProfilePepId() {
		return this.profilePepId;
	}

	public void setProfilePepId(long profilePepId) {
		this.profilePepId = profilePepId;
	}

	@Column(name = "PROFILE_PEP_NAME", length = 30)
	public String getProfilePepName() {
		return this.profilePepName;
	}

	public void setProfilePepName(String profilePepName) {
		this.profilePepName = profilePepName;
	}

	@Column(name = "QOS_ID")
	public Long getQosId() {
		return this.qosId;
	}

	public void setQosId(Long qosId) {
		this.qosId = qosId;
	}

	@Column(name = "MONITOR_KEY")
	public Long getMonitorKey() {
		return this.monitorKey;
	}

	public void setMonitorKey(Long monitorKey) {
		this.monitorKey = monitorKey;
	}

	@Column(name = "PRIORITY")
	public Long getPriority() {
		return this.priority;
	}

	public void setPriority(Long priority) {
		this.priority = priority;
	}

	@Column(name = "CATEGORY_ID")
	public Long getCategoryId() {
		return categoryId;
	}

	@Override
	@Transient
	public String getNodeName() {
		return profilePepName;
	}

	private Long domainId;
	private Long index;

	@Column(name = "DOMAIN_ID")
	public Long getDomainId() {
		return domainId;
	}

	public void setDomainId(Long domainId) {
		this.domainId = domainId;
	}

	public void setCategoryId(Long categoryId) {
		this.categoryId = categoryId;
	}

	@Column(name = "REMARK")
	public String getRemark() {
		return remark;
	}

	public void setRemark(String remark) {
		this.remark = remark;
	}

	@Column(name = "POS_INDEX", length = 20)
	public Long getIndex() {
		return index;
	}

	public void setIndex(Long index) {
		this.index = index;
	}

	@Override
	public ProfilePep clone() throws CloneNotSupportedException {
		return (ProfilePep) super.clone();
	}

}
