package com.viettel.ocs.entity;

// Generated Sep 2, 2016 4:54:08 PM by Hibernate Tools 3.2.1.GA

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Transient;

/**
 * ProfilePepPcc generated by hbm2java
 */
@Entity
@Table(name = "profile_pep_pcc")
public class ProfilePepPcc extends BaseEntity implements java.io.Serializable {

	@Override
	@Transient
	public String getNodeName() {
		return null;
	}

	private Long domainId;
	private long profilePepPccId;
	private Long pccRuleId;
	private Long profilePepId;

	public ProfilePepPcc() {
	}

	public ProfilePepPcc(Long pccRuleId, Long profilePepId) {
		this.pccRuleId = pccRuleId;
		this.profilePepId = profilePepId;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "PROFILE_PEP_PCC_ID", unique = true, nullable = false)
	public long getProfilePepPccId() {
		return this.profilePepPccId;
	}

	public void setProfilePepPccId(long profilePepPccId) {
		this.profilePepPccId = profilePepPccId;
	}

	@Column(name = "PCC_RULE_ID")
	public Long getPccRuleId() {
		return this.pccRuleId;
	}

	public void setPccRuleId(Long pccRuleId) {
		this.pccRuleId = pccRuleId;
	}

	@Column(name = "PROFILE_PEP_ID")
	public Long getProfilePepId() {
		return this.profilePepId;
	}

	public void setProfilePepId(Long profilePepId) {
		this.profilePepId = profilePepId;
	}

	@Column(name = "DOMAIN_ID")
	public Long getDomainId() {
		return domainId;
	}

	public void setDomainId(Long domainId) {
		this.domainId = domainId;
	}

}
