package com.viettel.ocs.entity;
// Generated Sep 2, 2016 4:54:08 PM by Hibernate Tools 3.2.1.GA


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Transient;

/**
 * PropList generated by hbm2java
 */
@Entity
@Table(name="prop_list"
)
public class PropList extends BaseEntity  implements java.io.Serializable {

	@Override
	@Transient
	public String getNodeName() {
		return null;
	}
	private Long domainId;
	@Column(name="DOMAIN_ID")
    public Long getDomainId() {
		return domainId;
	}
	public void setDomainId(Long domainId) {
		this.domainId = domainId;
	}
     private long propId;
     private String propName;
     private Long propTreeTypeId;
     private Long cycleTypeId;
     private Long cycleValue;
     private Long state;
     private String remark;
     private Long propTypeId;
     private Long propCatId;
     private String propMask;

    public PropList() {
    }

    public PropList(String propName, Long propTreeTypeId, Long cycleTypeId, Long cycleValue, Long state, String remark, Long propTypeId, Long propCatId, String propMask) {
       this.propName = propName;
       this.propTreeTypeId = propTreeTypeId;
       this.cycleTypeId = cycleTypeId;
       this.cycleValue = cycleValue;
       this.state = state;
       this.remark = remark;
       this.propTypeId = propTypeId;
       this.propCatId = propCatId;
       this.propMask = propMask;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)
    
    @Column(name="PROP_ID", unique=true, nullable=false)
    public long getPropId() {
        return this.propId;
    }
    
    public void setPropId(long propId) {
        this.propId = propId;
    }
    
    @Column(name="PROP_NAME", length=50)
    public String getPropName() {
        return this.propName;
    }
    
    public void setPropName(String propName) {
        this.propName = propName;
    }
    
    @Column(name="PROP_TREE_TYPE_ID")
    public Long getPropTreeTypeId() {
        return this.propTreeTypeId;
    }
    
    public void setPropTreeTypeId(Long propTreeTypeId) {
        this.propTreeTypeId = propTreeTypeId;
    }
    
    @Column(name="CYCLE_TYPE_ID")
    public Long getCycleTypeId() {
        return this.cycleTypeId;
    }
    
    public void setCycleTypeId(Long cycleTypeId) {
        this.cycleTypeId = cycleTypeId;
    }
    
    @Column(name="CYCLE_VALUE")
    public Long getCycleValue() {
        return this.cycleValue;
    }
    
    public void setCycleValue(Long cycleValue) {
        this.cycleValue = cycleValue;
    }
    
    @Column(name="STATE")
    public Long getState() {
        return this.state;
    }
    
    public void setState(Long state) {
        this.state = state;
    }
    
    @Column(name="REMARK", length=200)
    public String getRemark() {
        return this.remark;
    }
    
    public void setRemark(String remark) {
        this.remark = remark;
    }
    
    @Column(name="PROP_TYPE_ID")
    public Long getPropTypeId() {
        return this.propTypeId;
    }
    
    public void setPropTypeId(Long propTypeId) {
        this.propTypeId = propTypeId;
    }
    
    @Column(name="PROP_CAT_ID")
    public Long getPropCatId() {
        return this.propCatId;
    }
    
    public void setPropCatId(Long propCatId) {
        this.propCatId = propCatId;
    }
    
    @Column(name="PROP_MASK", length=200)
    public String getPropMask() {
        return this.propMask;
    }
    
    public void setPropMask(String propMask) {
        this.propMask = propMask;
    }




}


