package com.viettel.ocs.entity;

// Generated Sep 2, 2016 4:54:08 PM by Hibernate Tools 3.2.1.GA

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Transient;

/**
 * Qos generated by hbm2java
 */
@Entity
@Table(name = "qos")
public class Qos extends BaseEntity implements java.io.Serializable {

	@Override
	@Transient
	public String getNodeName() {
		return qosName;
	}

	private long qosId;
	private String qosName;
	private String qci;
	private Long mbrul;
	private Long mbrdl;
	private Long gbrul;
	private Long gbrdl;
	private String remark;
	private Long domainId;

	public Qos() {
	}

	public Qos(String qosName, String qci, Long mbrul, Long mbrdl, Long gbrul,
			Long gbrdl, String remark) {
		this.qosName = qosName;
		this.qci = qci;
		this.mbrul = mbrul;
		this.mbrdl = mbrdl;
		this.gbrul = gbrul;
		this.gbrdl = gbrdl;
		this.remark = remark;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "QOS_ID", unique = true, nullable = false)
	public long getQosId() {
		return this.qosId;
	}

	public void setQosId(long qosId) {
		this.qosId = qosId;
	}

	@Column(name = "QOS_NAME", length = 30)
	public String getQosName() {
		return this.qosName;
	}

	public void setQosName(String qosName) {
		this.qosName = qosName;
	}

	@Column(name = "QCI", length = 30)
	public String getQci() {
		return this.qci;
	}

	public void setQci(String qci) {
		this.qci = qci;
	}

	@Column(name = "MBRUL")
	public Long getMbrul() {
		return this.mbrul;
	}

	public void setMbrul(Long mbrul) {
		this.mbrul = mbrul;
	}

	@Column(name = "MBRDL")
	public Long getMbrdl() {
		return this.mbrdl;
	}

	public void setMbrdl(Long mbrdl) {
		this.mbrdl = mbrdl;
	}

	@Column(name = "GBRUL")
	public Long getGbrul() {
		return this.gbrul;
	}

	public void setGbrul(Long gbrul) {
		this.gbrul = gbrul;
	}

	@Column(name = "GBRDL")
	public Long getGbrdl() {
		return this.gbrdl;
	}

	public void setGbrdl(Long gbrdl) {
		this.gbrdl = gbrdl;
	}

	@Column(name = "QOS_REMARK")
	public String getRemark() {
		return remark;
	}

	public void setRemark(String remark) {
		this.remark = remark;
	}

	@Column(name = "DOMAIN_ID")
	public Long getDomainId() {
		return domainId;
	}

	public void setDomainId(Long domainId) {
		this.domainId = domainId;
	}
}
