package com.viettel.ocs.entity;
// Generated Sep 2, 2016 4:54:08 PM by Hibernate Tools 3.2.1.GA

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Transient;

/**
 * RateTable generated by hbm2java
 */
@Entity
@Table(name = "rate_table")
public class RateTable extends BaseEntity implements java.io.Serializable, Cloneable {

	@Override
	@Transient
	public String getNodeName() {
		return this.rateTableName;
	}

	private Long domainId;

	@Column(name = "DOMAIN_ID")
	public Long getDomainId() {
		return domainId;
	}

	public void setDomainId(Long domainId) {
		this.domainId = domainId;
	}

	private long rateTableId;
	private String rateTableName;
	private Long categoryId;
	private String remark;
	private Long state;
	private String externalId;
	private Long formulaId;
	private Long defaultFormulaId;
	private Long decisionTableId;
	private Long index;
	private Boolean generated;
	private Long unitTypeId;

	public RateTable() {
	}

	public RateTable(String rateTableName, Long categoryId, String remark, Long state, String externalId,
			Long formulaId, Long defaultFormulaId, Long decisionTableId, Long unitTypeId) {
		this.rateTableName = rateTableName;
		this.categoryId = categoryId;
		this.remark = remark;
		this.state = state;
		this.externalId = externalId;
		this.formulaId = formulaId;
		this.defaultFormulaId = defaultFormulaId;
		this.decisionTableId = decisionTableId;
		this.unitTypeId = unitTypeId;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "RATE_TABLE_ID", unique = true, nullable = false)
	public long getRateTableId() {
		return this.rateTableId;
	}

	public void setRateTableId(long rateTableId) {
		this.rateTableId = rateTableId;
	}

	@Column(name = "RATE_TABLE_NAME", length = 65535)
	public String getRateTableName() {
		return this.rateTableName;
	}

	public void setRateTableName(String rateTableName) {
		this.rateTableName = rateTableName;
	}

	@Column(name = "CATEGORY_ID")
	public Long getCategoryId() {
		return this.categoryId;
	}

	public void setCategoryId(Long categoryId) {
		this.categoryId = categoryId;
	}

	@Column(name = "REMARK", length = 65535)
	public String getRemark() {
		return this.remark;
	}

	public void setRemark(String remark) {
		this.remark = remark;
	}

	@Column(name = "STATE")
	public Long getState() {
		return this.state;
	}

	public void setState(Long state) {
		this.state = state;
	}

	@Column(name = "EXTERNAL_ID", length = 65535)
	public String getExternalId() {
		return this.externalId;
	}

	public void setExternalId(String externalId) {
		this.externalId = externalId;
	}

	@Column(name = "FORMULA_ID")
	public Long getFormulaId() {
		return this.formulaId;
	}

	public void setFormulaId(Long formulaId) {
		this.formulaId = formulaId;
	}

	@Column(name = "DEFAULT_FORMULA_ID")
	public Long getDefaultFormulaId() {
		return this.defaultFormulaId;
	}

	public void setDefaultFormulaId(Long defaultFormulaId) {
		this.defaultFormulaId = defaultFormulaId;
	}

	@Column(name = "DECISION_TABLE_ID")
	public Long getDecisionTableId() {
		return this.decisionTableId;
	}

	public void setDecisionTableId(Long decisionTableId) {
		this.decisionTableId = decisionTableId;
	}

	@Column(name = "POS_INDEX")
	public Long getIndex() {
		return index;
	}

	public void setIndex(Long index) {
		this.index = index;
	}

	@Column(name = "IS_GENERATED")
	public Boolean isGenerated() {
		return generated;
	}

	public void setGenerated(Boolean generated) {
		this.generated = generated;
	}
	
	@Column(name = "UNIT_TYPE_ID")
	public Long getUnitTypeId() {
		return unitTypeId;
	}

	public void setUnitTypeId(Long unitTypeId) {
		this.unitTypeId = unitTypeId;
	}

	@Override
	public RateTable clone() throws CloneNotSupportedException {
		// TODO Auto-generated method stub
		return (RateTable) super.clone();
	}

}
