package com.viettel.ocs.entity;
// Generated Sep 2, 2016 4:54:08 PM by Hibernate Tools 3.2.1.GA


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Transient;

/**
 * RateTableResult generated by hbm2java
 */
@Entity
@Table(name="rate_table_result"
)
public class RateTableResult extends BaseEntity  implements java.io.Serializable {

	@Override
	@Transient
	public String getNodeName() {
		return null;
	}
	private Long domainId;
	@Column(name="DOMAIN_ID")
    public Long getDomainId() {
		return domainId;
	}
	public void setDomainId(Long domainId) {
		this.domainId = domainId;
	}
     private long rateTableResultId;
     private Long rowIndex;
     private Long formulaId;

    public RateTableResult() {
    }

    public RateTableResult(Long rowIndex, Long formulaId) {
       this.rowIndex = rowIndex;
       this.formulaId = formulaId;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)
    
    @Column(name="RATE_TABLE_RESULT_ID", unique=true, nullable=false)
    public long getRateTableResultId() {
        return this.rateTableResultId;
    }
    
    public void setRateTableResultId(long rateTableResultId) {
        this.rateTableResultId = rateTableResultId;
    }
    
    @Column(name="ROW_INDEX")
    public Long getRowIndex() {
        return this.rowIndex;
    }
    
    public void setRowIndex(Long rowIndex) {
        this.rowIndex = rowIndex;
    }
    
    @Column(name="FORMULA_ID")
    public Long getFormulaId() {
        return this.formulaId;
    }
    
    public void setFormulaId(Long formulaId) {
        this.formulaId = formulaId;
    }




}


