package com.viettel.ocs.entity;
// Generated Sep 2, 2016 4:54:08 PM by Hibernate Tools 3.2.1.GA


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Transient;

/**
 * RedirectAddressSuspend generated by hbm2java
 */
@Entity
@Table(name="redirect_address_suspend"
)
public class RedirectAddressSuspend extends BaseEntity  implements java.io.Serializable {

	@Override
	@Transient
	public String getNodeName() {
		return null;
	}
	private Long domainId;
	@Column(name="DOMAIN_ID")
    public Long getDomainId() {
		return domainId;
	}
	public void setDomainId(Long domainId) {
		this.domainId = domainId;
	}
     private long redirectAddressSuspendId;
     private Long offerId;
     private String redirectAddress;

    public RedirectAddressSuspend() {
    }

    public RedirectAddressSuspend(Long offerId, String redirectAddress) {
       this.offerId = offerId;
       this.redirectAddress = redirectAddress;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)
    
    @Column(name="REDIRECT_ADDRESS_SUSPEND_ID", unique=true, nullable=false)
    public long getRedirectAddressSuspendId() {
        return this.redirectAddressSuspendId;
    }
    
    public void setRedirectAddressSuspendId(long redirectAddressSuspendId) {
        this.redirectAddressSuspendId = redirectAddressSuspendId;
    }
    
    @Column(name="OFFER_ID")
    public Long getOfferId() {
        return this.offerId;
    }
    
    public void setOfferId(Long offerId) {
        this.offerId = offerId;
    }
    
    @Column(name="REDIRECT_ADDRESS", length=200)
    public String getRedirectAddress() {
        return this.redirectAddress;
    }
    
    public void setRedirectAddress(String redirectAddress) {
        this.redirectAddress = redirectAddress;
    }




}


