package com.viettel.ocs.entity;
// Generated Sep 2, 2016 4:54:08 PM by Hibernate Tools 3.2.1.GA


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Transient;

/**
 * RelativeProduct generated by hbm2java
 */
@Entity
@Table(name="relative_product"
)
public class RelativeProduct extends BaseEntity  implements java.io.Serializable {

	@Override
	@Transient
	public String getNodeName() {
		return null;
	}
	private Long domainId;
	@Column(name="DOMAIN_ID")
    public Long getDomainId() {
		return domainId;
	}
	public void setDomainId(Long domainId) {
		this.domainId = domainId;
	}
     private long relativeProductId;
     private Long mainProdSpecId;
     private Long subProdSpecId;
     private Long addOn;
     private Long exchangable;

    public RelativeProduct() {
    }

    public RelativeProduct(Long mainProdSpecId, Long subProdSpecId, Long addOn, Long exchangable) {
       this.mainProdSpecId = mainProdSpecId;
       this.subProdSpecId = subProdSpecId;
       this.addOn = addOn;
       this.exchangable = exchangable;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)
    
    @Column(name="RELATIVE_PRODUCT_ID", unique=true, nullable=false)
    public long getRelativeProductId() {
        return this.relativeProductId;
    }
    
    public void setRelativeProductId(long relativeProductId) {
        this.relativeProductId = relativeProductId;
    }
    
    @Column(name="MAIN_PROD_SPEC_ID")
    public Long getMainProdSpecId() {
        return this.mainProdSpecId;
    }
    
    public void setMainProdSpecId(Long mainProdSpecId) {
        this.mainProdSpecId = mainProdSpecId;
    }
    
    @Column(name="SUB_PROD_SPEC_ID")
    public Long getSubProdSpecId() {
        return this.subProdSpecId;
    }
    
    public void setSubProdSpecId(Long subProdSpecId) {
        this.subProdSpecId = subProdSpecId;
    }
    
    @Column(name="ADD_ON")
    public Long getAddOn() {
        return this.addOn;
    }
    
    public void setAddOn(Long addOn) {
        this.addOn = addOn;
    }
    
    @Column(name="EXCHANGABLE")
    public Long getExchangable() {
        return this.exchangable;
    }
    
    public void setExchangable(Long exchangable) {
        this.exchangable = exchangable;
    }




}


