package com.viettel.ocs.entity;
// Generated Sep 2, 2016 4:54:08 PM by Hibernate Tools 3.2.1.GA


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Transient;

/**
 * ReserveInfoActionMap generated by hbm2java
 */
@Entity
@Table(name="reserve_info_action_map"
)
public class ReserveInfoActionMap extends BaseEntity  implements java.io.Serializable {

	@Override
	@Transient
	public String getNodeName() {
		return null;
	}
	private Long domainId;
	@Column(name="DOMAIN_ID")
    public Long getDomainId() {
		return domainId;
	}
	public void setDomainId(Long domainId) {
		this.domainId = domainId;
	}
     private long reserveInfoActionMapId;
     private Long reserveInfoId;
     private Long actionId;

    public ReserveInfoActionMap() {
    }

    public ReserveInfoActionMap(Long reserveInfoId, Long actionId) {
       this.reserveInfoId = reserveInfoId;
       this.actionId = actionId;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)
    
    @Column(name="RESERVE_INFO_ACTION_MAP_ID", unique=true, nullable=false)
    public long getReserveInfoActionMapId() {
        return this.reserveInfoActionMapId;
    }
    
    public void setReserveInfoActionMapId(long reserveInfoActionMapId) {
        this.reserveInfoActionMapId = reserveInfoActionMapId;
    }
    
    @Column(name="RESERVE_INFO_ID")
    public Long getReserveInfoId() {
        return this.reserveInfoId;
    }
    
    public void setReserveInfoId(Long reserveInfoId) {
        this.reserveInfoId = reserveInfoId;
    }
    
    @Column(name="ACTION_ID")
    public Long getActionId() {
        return this.actionId;
    }
    
    public void setActionId(Long actionId) {
        this.actionId = actionId;
    }




}


