package com.viettel.ocs.entity;
// Generated Sep 2, 2016 4:54:08 PM by Hibernate Tools 3.2.1.GA

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Transient;

/**
 * ResultRateMap generated by hbm2java
 */
@Entity
@Table(name = "result_rate_map")
public class ResultRateMap extends BaseEntity implements java.io.Serializable {

	@Override
	@Transient
	public String getNodeName() {
		return null;
	}

	private Long domainId;

	@Column(name = "DOMAIN_ID")
	public Long getDomainId() {
		return domainId;
	}

	public void setDomainId(Long domainId) {
		this.domainId = domainId;
	}

	private long resultRateMapId;
	private Long rateTableId;
	private Long rateTableResultId;

	public ResultRateMap() {
	}

	public ResultRateMap(Long rateTableId, Long rateTableResultId) {
		this.rateTableId = rateTableId;
		this.rateTableResultId = rateTableResultId;
	}

	public ResultRateMap(Long rateTableId, Long rateTableResultId, Long domainId) {
		this.rateTableId = rateTableId;
		this.rateTableResultId = rateTableResultId;
		this.domainId = domainId;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "RESULT_RATE_MAP_ID", unique = true, nullable = false)
	public long getResultRateMapId() {
		return this.resultRateMapId;
	}

	public void setResultRateMapId(long resultRateMapId) {
		this.resultRateMapId = resultRateMapId;
	}

	@Column(name = "RATE_TABLE_ID")
	public Long getRateTableId() {
		return this.rateTableId;
	}

	public void setRateTableId(Long rateTableId) {
		this.rateTableId = rateTableId;
	}

	@Column(name = "RATE_TABLE_RESULT_ID")
	public Long getRateTableResultId() {
		return this.rateTableResultId;
	}

	public void setRateTableResultId(Long rateTableResultId) {
		this.rateTableResultId = rateTableResultId;
	}

}
