package com.viettel.ocs.entity;
// Generated Sep 2, 2016 4:54:08 PM by Hibernate Tools 3.2.1.GA

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Transient;

/**
 * RowDt generated by hbm2java
 */
@Entity
@Table(name = "row_dt")
public class RowDt extends BaseEntity implements java.io.Serializable, Cloneable {

	@Override
	@Transient
	public String getNodeName() {
		return null;
	}

	private Long domainId;

	@Column(name = "DOMAIN_ID")
	public Long getDomainId() {
		return domainId;
	}

	public void setDomainId(Long domainId) {
		this.domainId = domainId;
	}

	private long rowId;
	private String value;
	private Integer rowIndex;
	private Boolean defaultValue = false;

	@Transient
	public Boolean getDefaultValue() {
		return defaultValue;
	}

	@Transient
	public void setDefaultValue(Boolean defaultValue) {
		this.defaultValue = defaultValue;
	}

	public RowDt() {
	}

	public RowDt(String value, Integer rowIndex) {
		this.value = value;
		this.rowIndex = rowIndex;
	}

	public RowDt(int rowId, String value, Integer rowIndex) {
		this.rowId = rowId;
		this.value = value;
		this.rowIndex = rowIndex;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "ROW_ID", unique = true, nullable = false)
	public long getRowId() {
		return this.rowId;
	}

	public void setRowId(long rowId) {
		this.rowId = rowId;
	}

	@Column(name = "VALUE", length = 200)
	public String getValue() {
		return this.value;
	}

	public void setValue(String value) {
		this.value = value;
	}

	@Column(name = "ROW_INDEX")
	public Integer getRowIndex() {
		return this.rowIndex;
	}

	public void setRowIndex(Integer rowIndex) {
		this.rowIndex = rowIndex;
	}

	@Override
	public RowDt clone() throws CloneNotSupportedException {
		return (RowDt) super.clone();
	}

}
