package com.viettel.ocs.entity;
// Generated Aug 9, 2016 8:58:38 AM by Hibernate Tools 3.2.1.GA

import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Transient;

/**
 * RowOcs generated by hbm2java
 */
@Entity
@Table(name="ROW_OCS"
    
)
public class RowOcs extends BaseEntity  implements java.io.Serializable {


     /**
	 * 
	 */
	private static final long serialVersionUID = -6562925803331542590L;
	private long rowOcsId;
     private Long rowIndexId;

     private Long domainId;
     
     @Column(name="DOMAIN_ID")
    public Long getDomainId() {
		return domainId;
	}

	public void setDomainId(Long domainId) {
		this.domainId = domainId;
	}
 	
    public RowOcs() {
    }

	
    public RowOcs(long rowOcsId) {
        this.rowOcsId = rowOcsId;
    }
    public RowOcs(long rowOcsId, Long rowIndexId) {
       this.rowOcsId = rowOcsId;
       this.rowIndexId = rowIndexId;
    }
   
     @Id @GeneratedValue(strategy=GenerationType.IDENTITY) 
    
    @Column(name="ROW_OCS_ID", unique=true, nullable=false, precision=14, scale=0)
    public long getRowOcsId() {
        return this.rowOcsId;
    }
    
    public void setRowOcsId(long rowOcsId) {
        this.rowOcsId = rowOcsId;
    }
    
    @Column(name="ROW_INDEX_ID", precision=6, scale=0)
    public Long getRowIndexId() {
        return this.rowIndexId;
    }
    
    public void setRowIndexId(Long rowIndexId) {
        this.rowIndexId = rowIndexId;
    }


	@Transient
	@Override
	public String getNodeName() {
		return null;
	}


}


