package com.viettel.ocs.entity;
// Generated Sep 2, 2016 4:54:08 PM by Hibernate Tools 3.2.1.GA

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;

import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Transient;

/**
 * SortPriceComponent generated by hbm2java
 */
@SuppressWarnings("serial")
@Entity
@Table(name = "sort_price_component")
public class SortPriceComponent extends BaseEntity implements java.io.Serializable, Cloneable {

	@Override
	@Transient
	public String getNodeName() {
		return sortPriceComponentName;
	}

	private Long domainId;

	@Column(name = "DOMAIN_ID")
	public Long getDomainId() {
		return domainId;
	}

	public void setDomainId(Long domainId) {
		this.domainId = domainId;
	}

	private long sortPriceComponentId;
	private String sortPriceComponentName;
	private Long categoryId;
	private String remark;
	private Long index;
	private Boolean generated;

	public SortPriceComponent() {
	}

	public SortPriceComponent(String sortPriceComponentName, Long categoryId, String remark) {
		this.sortPriceComponentName = sortPriceComponentName;
		this.categoryId = categoryId;
		this.remark = remark;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "SORT_PRICE_COMPONENT_ID", unique = true, nullable = false)
	public long getSortPriceComponentId() {
		return this.sortPriceComponentId;
	}

	public void setSortPriceComponentId(long sortPriceComponentId) {
		this.sortPriceComponentId = sortPriceComponentId;
	}

	@Column(name = "SORT_PRICE_COMPONENT_NAME", length = 65535)
	public String getSortPriceComponentName() {
		return this.sortPriceComponentName;
	}

	public void setSortPriceComponentName(String sortPriceComponentName) {
		this.sortPriceComponentName = sortPriceComponentName;
	}

	@Column(name = "CATEGORY_ID")
	public Long getCategoryId() {
		return this.categoryId;
	}

	public void setCategoryId(Long categoryId) {
		this.categoryId = categoryId;
	}

	@Column(name = "REMARK", length = 65535)
	public String getRemark() {
		return this.remark;
	}

	public void setRemark(String remark) {
		this.remark = remark;
	}

	@Column(name = "POS_INDEX")
	public Long getIndex() {
		return index;
	}

	public void setIndex(Long index) {
		this.index = index;
	}

	@Column(name = "IS_GENERATED")
	public Boolean isGenerated() {
		return generated;
	}

	public void setGenerated(Boolean generated) {
		this.generated = generated;
	}

	@Override
	public SortPriceComponent clone() throws CloneNotSupportedException {
		return (SortPriceComponent) super.clone();
	}

}
