package com.viettel.ocs.entity;
// Generated Sep 2, 2016 4:54:08 PM by Hibernate Tools 3.2.1.GA

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;

import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Transient;

/**
 * StateType generated by hbm2java
 */
@Entity
@Table(name = "state_type")
public class StateType extends BaseEntity implements java.io.Serializable {

	@Override
	@Transient
	public String getNodeName() {
		return this.stateName;
	}

	private Long domainId;

	@Column(name = "DOMAIN_ID")
	public Long getDomainId() {
		return domainId;
	}

	public void setDomainId(Long domainId) {
		this.domainId = domainId;
	}

	private long stateTypeId;
	private String stateName;
	private Long stateType;
	private Long stateGroupId;
	private String stateDesc;
	private String stateMask;
	private String filterValue;
	private boolean status;
	private Long categoryId;
	private Boolean stateStatus;

	public StateType() {
	}

	public StateType(String stateName, Long stateType, Long stateGroupId, String stateDesc, String stateMask,
			String filterValue, boolean status, Long categoryId) {
		this.stateName = stateName;
		this.stateType = stateType;
		this.stateGroupId = stateGroupId;
		this.stateDesc = stateDesc;
		this.stateMask = stateMask;
		this.filterValue = filterValue;
		this.status = status;
		this.categoryId = categoryId;
	}

	@Id
	@Column(name = "STATE_TYPE_ID", unique = true, nullable = false)
	public long getStateTypeId() {
		return this.stateTypeId;
	}

	public void setStateTypeId(long stateTypeId) {
		this.stateTypeId = stateTypeId;
	}

	@Column(name = "STATE_NAME", length = 200)
	public String getStateName() {
		return this.stateName;
	}

	public void setStateName(String stateName) {
		this.stateName = stateName;
	}

	@Column(name = "STATE_TYPE")
	public Long getStateType() {
		return this.stateType;
	}

	public void setStateType(Long stateType) {
		this.stateType = stateType;
	}

	@Column(name = "STATE_GROUP_ID")
	public Long getStateGroupId() {
		return this.stateGroupId;
	}

	public void setStateGroupId(Long stateGroupId) {
		this.stateGroupId = stateGroupId;
	}

	@Column(name = "STATE_DESC", length = 200)
	public String getStateDesc() {
		return this.stateDesc;
	}

	public void setStateDesc(String stateDesc) {
		this.stateDesc = stateDesc;
	}

	@Column(name = "STATE_MASK", length = 20)
	public String getStateMask() {
		return this.stateMask;
	}

	public void setStateMask(String stateMask) {
		this.stateMask = stateMask;
	}

	@Column(name = "FILTER_VALUE", length = 20)
	public String getFilterValue() {
		return this.filterValue;
	}

	public void setFilterValue(String filterValue) {
		this.filterValue = filterValue;
	}

	@Column(name = "STATUS")
	public boolean getStatus() {
		return this.status;
	}

	public void setStatus(boolean status) {
		this.status = status;
	}

	@Column(name = "CATEGORY_ID")
	public Long getCategoryId() {
		return this.categoryId;
	}

	public void setCategoryId(Long categoryId) {
		this.categoryId = categoryId;
	}

	@Column(name = "STATE_STATUS")
	public Boolean getStateStatus() {
		return stateStatus;
	}

	public void setStateStatus(Boolean stateStatus) {
		this.stateStatus = stateStatus;
	}

	private Long index;

	@GeneratedValue(strategy = GenerationType.AUTO)
	@Column(name = "STATE_INDEX")
	public Long getIndex() {
		return index;
	}

	public void setIndex(Long Index) {
		this.index = Index;
	}
}
