package com.viettel.ocs.entity;
// Generated Sep 2, 2016 4:54:08 PM by Hibernate Tools 3.2.1.GA

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Transient;

/**
 * ThresholdBaltypeMap generated by hbm2java
 */
@Entity
@Table(name = "threshold_baltype_map")
public class ThresholdBaltypeMap extends BaseEntity implements java.io.Serializable {

	@Override
	@Transient
	public String getNodeName() {
		return null;
	}

	private Long domainId;

	@Column(name = "DOMAIN_ID")
	public Long getDomainId() {
		return domainId;
	}

	public void setDomainId(Long domainId) {
		this.domainId = domainId;
	}

	private long thresholdBaltypeMapId;
	private Long thresholdId;
	private Long balTypeId;

	public ThresholdBaltypeMap() {
	}

	public ThresholdBaltypeMap(Long thresholdId, Long balTypeId) {
		this.thresholdId = thresholdId;
		this.balTypeId = balTypeId;
	}

	public ThresholdBaltypeMap(Long thresholdId, Long balTypeId, Long domainId) {
		this.thresholdId = thresholdId;
		this.balTypeId = balTypeId;
		this.domainId = domainId;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "THRESHOLD_BALTYPE_MAP_ID", unique = true, nullable = false)
	public long getThresholdBaltypeMapId() {
		return this.thresholdBaltypeMapId;
	}

	public void setThresholdBaltypeMapId(long thresholdBaltypeMapId) {
		this.thresholdBaltypeMapId = thresholdBaltypeMapId;
	}

	@Column(name = "THRESHOLD_ID")
	public Long getThresholdId() {
		return this.thresholdId;
	}

	public void setThresholdId(Long thresholdId) {
		this.thresholdId = thresholdId;
	}

	@Column(name = "BALTYPE_ID")
	public Long getBalTypeId() {
		return this.balTypeId;
	}

	public void setBalTypeId(Long balTypeId) {
		this.balTypeId = balTypeId;
	}

}
