package com.viettel.ocs.entity;
// Generated Sep 2, 2016 4:54:08 PM by Hibernate Tools 3.2.1.GA

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;

import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Transient;

/**
 * TriggerOcs generated by hbm2java
 */
@Entity
@Table(name = "trigger_ocs")
public class TriggerOcs extends BaseEntity implements java.io.Serializable {

	@Override
	@Transient
	public String getNodeName() {
		return this.triggerName;
	}

	private Long domainId;

	@Column(name = "DOMAIN_ID")
	public Long getDomainId() {
		return domainId;
	}

	public void setDomainId(Long domainId) {
		this.domainId = domainId;
	}

	private long triggerOcsId;
	private String description;
	private String triggerName;
	private String extProperty;
	private Long triggerType;
	private Boolean status;
	private Long module;
	private Long categoryId;
	private Long index;

	public TriggerOcs() {
	}

	public TriggerOcs(String description, String triggerName, Long triggerType, Boolean status, Long module) {
		this.description = description;
		this.triggerName = triggerName;
		this.triggerType = triggerType;
		this.status = status;
		this.module = module;
	}

	@Column(name = "CATEGORY_ID")
	public Long getCategoryId() {
		return categoryId;
	}

	public void setCategoryId(Long categoryId) {
		this.categoryId = categoryId;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "TRIGGER_OCS_ID", unique = true, nullable = false)
	public long getTriggerOcsId() {
		return this.triggerOcsId;
	}

	public void setTriggerOcsId(long triggerOcsId) {
		this.triggerOcsId = triggerOcsId;
	}

	@Column(name = "DESCRIPTION", length = 65535)
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@Column(name = "TRIGGER_NAME", length = 65535)
	public String getTriggerName() {
		return this.triggerName;
	}

	public void setTriggerName(String triggerName) {
		this.triggerName = triggerName;
	}

	@Column(name = "TRIGGER_TYPE")
	public Long getTriggerType() {
		return this.triggerType;
	}

	public void setTriggerType(Long triggerType) {
		this.triggerType = triggerType;
	}

	@Column(name = "STATUS")
	public Boolean getStatus() {
		return this.status;
	}

	public void setStatus(Boolean status) {
		this.status = status;
	}

	public Long getModule() {
		return this.module;
	}

	public void setModule(Long module) {
		this.module = module;
	}

	@Column(name = "EXT_PROPERTY")
	public String getExtProperty() {
		return extProperty;
	}

	public void setExtProperty(String extProperty) {
		this.extProperty = extProperty;
	}

	@Column(name = "POS_INDEX")
	public Long getIndex() {
		return index;
	}

	public void setIndex(Long index) {
		this.index = index;
	}

}
