package com.viettel.ocs.entity;
// Generated Sep 2, 2016 4:54:08 PM by Hibernate Tools 3.2.1.GA

import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Transient;

/**
 * TriggerType generated by hbm2java
 */
@Entity
@Table(name = "trigger_type")
public class TriggerType extends BaseEntity implements java.io.Serializable {

	@Override
	@Transient
	public String getNodeName() {
		return this.triggerTypeName;
	}

	private Long domainId;

	@Column(name = "DOMAIN_ID")
	public Long getDomainId() {
		return domainId;
	}

	public void setDomainId(Long domainId) {
		this.domainId = domainId;
	}

	private long triggerType;
	private String triggerTypeName;
	private String triggerTypeDescription;
	private Long categoryId;
	private Long index;

	public TriggerType() {
	}

	public TriggerType(String triggerTypeName, String triggerTypeDescription) {
		this.triggerTypeName = triggerTypeName;
		this.triggerTypeDescription = triggerTypeDescription;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "TRIGGER_TYPE", unique = true, nullable = false)
	public long getTriggerType() {
		return this.triggerType;
	}

	public void setTriggerType(long triggerType) {
		this.triggerType = triggerType;
	}

	@Column(name = "TRIGGER_TYPE_NAME", length = 100)
	public String getTriggerTypeName() {
		return this.triggerTypeName;
	}

	public void setTriggerTypeName(String triggerTypeName) {
		this.triggerTypeName = triggerTypeName;
	}

	@Column(name = "TRIGGER_TYPE_DESCRIPTION", length = 65535)
	public String getTriggerTypeDescription() {
		return this.triggerTypeDescription;
	}

	public void setTriggerTypeDescription(String triggerTypeDescription) {
		this.triggerTypeDescription = triggerTypeDescription;
	}

	@Column(name = "CATEGORY_ID")
	public Long getCategoryId() {
		return this.categoryId;
	}

	public void setCategoryId(Long categoryId) {
		this.categoryId = categoryId;
	}

	@Column(name = "POS_INDEX")
	public Long getIndex() {
		return index;
	}

	public void setIndex(Long index) {
		this.index = index;
	}
}
