package com.viettel.ocs.entity;
// Generated Sep 2, 2016 4:54:08 PM by Hibernate Tools 3.2.1.GA


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Transient;

/**
 * TriggerEvent generated by hbm2java
 */
@Entity
@Table(name="trigger_event"
)
public class TriggerEvent extends BaseEntity  implements java.io.Serializable {

	@Override
	@Transient
	public String getNodeName() {
		return null;
	}
	private Long domainId;
	@Column(name="DOMAIN_ID")
    public Long getDomainId() {
		return domainId;
	}
	public void setDomainId(Long domainId) {
		this.domainId = domainId;
	}
     private long triggerEventId;
     private long triggerOcsId;
     private String triggerEventName;
     private long categoryId;
     private Long destinationId;
     private Long triggerEventType;
     private Long status;
     private Long delayProcess;

    public TriggerEvent() {
    }

	
    public TriggerEvent(long triggerOcsId, long categoryId) {
        this.triggerOcsId = triggerOcsId;
        this.categoryId = categoryId;
    }
    public TriggerEvent(long triggerOcsId, String triggerEventName, long categoryId, Long destinationId, Long triggerEventType, Long status, Long delayProcess) {
       this.triggerOcsId = triggerOcsId;
       this.triggerEventName = triggerEventName;
       this.categoryId = categoryId;
       this.destinationId = destinationId;
       this.triggerEventType = triggerEventType;
       this.status = status;
       this.delayProcess = delayProcess;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)
    
    @Column(name="TRIGGER_EVENT_ID", unique=true, nullable=false)
    public long getTriggerEventId() {
        return this.triggerEventId;
    }
    
    public void setTriggerEventId(long triggerEventId) {
        this.triggerEventId = triggerEventId;
    }
    
    @Column(name="TRIGGER_OCS_ID", nullable=false)
    public long getTriggerOcsId() {
        return this.triggerOcsId;
    }
    
    public void setTriggerOcsId(long triggerOcsId) {
        this.triggerOcsId = triggerOcsId;
    }
    
    @Column(name="TRIGGER_EVENT_NAME", length=40)
    public String getTriggerEventName() {
        return this.triggerEventName;
    }
    
    public void setTriggerEventName(String triggerEventName) {
        this.triggerEventName = triggerEventName;
    }
    
    @Column(name="CATEGORY_ID", nullable=false)
    public long getCategoryId() {
        return this.categoryId;
    }
    
    public void setCategoryId(long categoryId) {
        this.categoryId = categoryId;
    }
    
    @Column(name="DESTINATION_ID")
    public Long getDestinationId() {
        return this.destinationId;
    }
    
    public void setDestinationId(Long destinationId) {
        this.destinationId = destinationId;
    }
    
    @Column(name="TRIGGER_EVENT_TYPE")
    public Long getTriggerEventType() {
        return this.triggerEventType;
    }
    
    public void setTriggerEventType(Long triggerEventType) {
        this.triggerEventType = triggerEventType;
    }
    
    @Column(name="STATUS")
    public Long getStatus() {
        return this.status;
    }
    
    public void setStatus(Long status) {
        this.status = status;
    }
    
    @Column(name="DELAY_PROCESS")
    public Long getDelayProcess() {
        return this.delayProcess;
    }
    
    public void setDelayProcess(Long delayProcess) {
        this.delayProcess = delayProcess;
    }




}


