package com.viettel.ocs.entity;
// Generated Sep 2, 2016 4:54:08 PM by Hibernate Tools 3.2.1.GA


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Transient;

/**
 * TriggerEventType generated by hbm2java
 */
@Entity
@Table(name="trigger_event_type"
)
public class TriggerEventType extends BaseEntity  implements java.io.Serializable {

	@Override
	@Transient
	public String getNodeName() {
		return null;
	}
	private Long domainId;
	@Column(name="DOMAIN_ID")
    public Long getDomainId() {
		return domainId;
	}
	public void setDomainId(Long domainId) {
		this.domainId = domainId;
	}
     private long triggerEventType;
     private String eventName;
     private String eventDescription;
     private String protocol;

    public TriggerEventType() {
    }

	
    public TriggerEventType(String eventName, String protocol) {
        this.eventName = eventName;
        this.protocol = protocol;
    }
    public TriggerEventType(String eventName, String eventDescription, String protocol) {
       this.eventName = eventName;
       this.eventDescription = eventDescription;
       this.protocol = protocol;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)
    
    @Column(name="TRIGGER_EVENT_TYPE", unique=true, nullable=false)
    public long getTriggerEventType() {
        return this.triggerEventType;
    }
    
    public void setTriggerEventType(long triggerEventType) {
        this.triggerEventType = triggerEventType;
    }
    
    @Column(name="EVENT_NAME", nullable=false, length=40)
    public String getEventName() {
        return this.eventName;
    }
    
    public void setEventName(String eventName) {
        this.eventName = eventName;
    }
    
    @Column(name="EVENT_DESCRIPTION", length=65535)
    public String getEventDescription() {
        return this.eventDescription;
    }
    
    public void setEventDescription(String eventDescription) {
        this.eventDescription = eventDescription;
    }
    
    @Column(name="PROTOCOL", nullable=false, length=20)
    public String getProtocol() {
        return this.protocol;
    }
    
    public void setProtocol(String protocol) {
        this.protocol = protocol;
    }




}


