package com.viettel.ocs.entity;
// Generated Sep 2, 2016 4:54:08 PM by Hibernate Tools 3.2.1.GA

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Transient;

/**
 * TriggerDestination generated by hbm2java
 */
@SuppressWarnings("serial")
@Entity
@Table(name = "trigger_destination")
public class TriggerDestination extends BaseEntity implements java.io.Serializable {

	@Override
	@Transient
	public String getNodeName() {
		return this.destName;
	}

	private Long domainId;

	@Column(name = "DOMAIN_ID")
	public Long getDomainId() {
		return domainId;
	}

	public void setDomainId(Long domainId) {
		this.domainId = domainId;
	}

	private long destinationId;
	private long categoryId;
	private String destName;
	private String destDescription;
	private Boolean status;
	private Long index;

	public TriggerDestination() {
	}

	public TriggerDestination(long categoryId, String destName) {
		this.categoryId = categoryId;
		this.destName = destName;
	}

	public TriggerDestination(long categoryId, String destName, String destDescription, Boolean status) {
		this.categoryId = categoryId;
		this.destName = destName;
		this.destDescription = destDescription;
		this.status = status;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "DESTINATION_ID", unique = true, nullable = false)
	public long getDestinationId() {
		return this.destinationId;
	}

	public void setDestinationId(long destinationId) {
		this.destinationId = destinationId;
	}

	@Column(name = "CATEGORY_ID", nullable = false)
	public long getCategoryId() {
		return this.categoryId;
	}

	public void setCategoryId(long categoryId) {
		this.categoryId = categoryId;
	}

	@Column(name = "DEST_NAME", nullable = false, length = 50)
	public String getDestName() {
		return this.destName;
	}

	public void setDestName(String destName) {
		this.destName = destName;
	}

	@Column(name = "DEST_DESCRIPTION", length = 65535)
	public String getDestDescription() {
		return this.destDescription;
	}

	public void setDestDescription(String destDescription) {
		this.destDescription = destDescription;
	}

	@Column(name = "STATUS")
	public Boolean getStatus() {
		return this.status;
	}

	public void setStatus(Boolean status) {
		this.status = status;
	}

	@Column(name = "POS_INDEX")
	public Long getIndex() {
		return index;
	}

	public void setIndex(Long index) {
		this.index = index;
	}

}
