package com.viettel.ocs.entity;
// Generated Sep 2, 2016 4:54:08 PM by Hibernate Tools 3.2.1.GA

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Transient;

/**
 * TriggerMsg generated by hbm2java
 */
@Entity
@Table(name = "trigger_msg")
public class TriggerMsg extends BaseEntity implements java.io.Serializable {

	@Override
	@Transient
	public String getNodeName() {
		return this.msgName;
	}

	private Long domainId;

	@Column(name = "DOMAIN_ID")
	public Long getDomainId() {
		return domainId;
	}

	public void setDomainId(Long domainId) {
		this.domainId = domainId;
	}

	private long msgId;
	private long triggerEventId;
	private String msgName;
	private String msgDesc;
	private boolean status;
	private Long categoryId;
	private Long index;

	public TriggerMsg() {
	}

	public TriggerMsg(long triggerEventId, String msgName) {
		this.triggerEventId = triggerEventId;
		this.msgName = msgName;
	}

	public TriggerMsg(long triggerEventId, String msgName, String msgDesc, boolean status) {
		this.triggerEventId = triggerEventId;
		this.msgName = msgName;
		this.msgDesc = msgDesc;
		this.status = status;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "MSG_ID", unique = true, nullable = false)
	public long getMsgId() {
		return this.msgId;
	}

	public void setMsgId(long msgId) {
		this.msgId = msgId;
	}

	@Column(name = "TRIGGER_EVENT_ID", nullable = false)
	public long getTriggerEventId() {
		return this.triggerEventId;
	}

	public void setTriggerEventId(long triggerEventId) {
		this.triggerEventId = triggerEventId;
	}

	@Column(name = "MSG_NAME", nullable = false, length = 50)
	public String getMsgName() {
		return this.msgName;
	}

	public void setMsgName(String msgName) {
		this.msgName = msgName;
	}

	@Column(name = "MSG_DESC", length = 65535)
	public String getMsgDesc() {
		return this.msgDesc;
	}

	public void setMsgDesc(String msgDesc) {
		this.msgDesc = msgDesc;
	}

	@Column(name = "STATUS")
	public boolean getStatus() {
		return this.status;
	}

	public void setStatus(boolean status) {
		this.status = status;
	}

	@Column(name = "CATEGORY_ID")
	public Long getCategoryId() {
		return categoryId;
	}

	public void setCategoryId(Long categoryId) {
		this.categoryId = categoryId;
	}

	@Column(name = "POS_INDEX")
	public Long getIndex() {
		return index;
	}

	public void setIndex(Long index) {
		this.index = index;
	}
}
