package com.viettel.ocs.entity;
// Generated Sep 2, 2016 4:54:08 PM by Hibernate Tools 3.2.1.GA


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Transient;

/**
 * TriggerMsgField generated by hbm2java
 */
@Entity
@Table(name="trigger_msg_field"
)
public class TriggerMsgField extends BaseEntity  implements java.io.Serializable {

	@Override
	@Transient
	public String getNodeName() {
		return null;
	}
	private Long domainId;
	@Column(name="DOMAIN_ID")
    public Long getDomainId() {
		return domainId;
	}
	public void setDomainId(Long domainId) {
		this.domainId = domainId;
	}
     private long msgFieldId;
     private long msgId;
     private long fieldBuilderId;
     private Long msgOrder;
     private Long msgStatus;

    public TriggerMsgField() {
    }

	
    public TriggerMsgField(long msgId, long fieldBuilderId) {
        this.msgId = msgId;
        this.fieldBuilderId = fieldBuilderId;
    }
    public TriggerMsgField(long msgId, long fieldBuilderId, Long msgOrder, Long msgStatus) {
       this.msgId = msgId;
       this.fieldBuilderId = fieldBuilderId;
       this.msgOrder = msgOrder;
       this.msgStatus = msgStatus;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)
    
    @Column(name="MSG_FIELD_ID", unique=true, nullable=false)
    public long getMsgFieldId() {
        return this.msgFieldId;
    }
    
    public void setMsgFieldId(long msgFieldId) {
        this.msgFieldId = msgFieldId;
    }
    
    @Column(name="MSG_ID", nullable=false)
    public long getMsgId() {
        return this.msgId;
    }
    
    public void setMsgId(long msgId) {
        this.msgId = msgId;
    }
    
    @Column(name="FIELD_BUILDER_ID", nullable=false)
    public long getFieldBuilderId() {
        return this.fieldBuilderId;
    }
    
    public void setFieldBuilderId(long fieldBuilderId) {
        this.fieldBuilderId = fieldBuilderId;
    }
    
    @Column(name="MSG_ORDER")
    public Long getMsgOrder() {
        return this.msgOrder;
    }
    
    public void setMsgOrder(Long msgOrder) {
        this.msgOrder = msgOrder;
    }
    
    @Column(name="MSG_STATUS")
    public Long getMsgStatus() {
        return this.msgStatus;
    }
    
    public void setMsgStatus(Long msgStatus) {
        this.msgStatus = msgStatus;
    }




}


