package com.viettel.ocs.entity;
// Generated Sep 2, 2016 4:54:08 PM by Hibernate Tools 3.2.1.GA


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Transient;

/**
 * TriggerFieldBuilder generated by hbm2java
 */
@Entity
@Table(name="trigger_field_builder"
)
public class TriggerFieldBuilder extends BaseEntity  implements java.io.Serializable {

	@Override
	@Transient
	public String getNodeName() {
		return null;
	}
	private Long domainId;
	@Column(name="DOMAIN_ID")
    public Long getDomainId() {
		return domainId;
	}
	public void setDomainId(Long domainId) {
		this.domainId = domainId;
	}
     private long fieldBuilderId;
     private String fieldName;
     private String processFunction;
     private long fieldListId;
     private Long formatTemplateId;
     private Long langId;
     private Long status;

    public TriggerFieldBuilder() {
    }

	
    public TriggerFieldBuilder(String fieldName, long fieldListId) {
        this.fieldName = fieldName;
        this.fieldListId = fieldListId;
    }
    public TriggerFieldBuilder(String fieldName, String processFunction, long fieldListId, Long formatTemplateId, Long langId, Long status) {
       this.fieldName = fieldName;
       this.processFunction = processFunction;
       this.fieldListId = fieldListId;
       this.formatTemplateId = formatTemplateId;
       this.langId = langId;
       this.status = status;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)
    
    @Column(name="FIELD_BUILDER_ID", unique=true, nullable=false)
    public long getFieldBuilderId() {
        return this.fieldBuilderId;
    }
    
    public void setFieldBuilderId(long fieldBuilderId) {
        this.fieldBuilderId = fieldBuilderId;
    }
    
    @Column(name="FIELD_NAME", nullable=false, length=80)
    public String getFieldName() {
        return this.fieldName;
    }
    
    public void setFieldName(String fieldName) {
        this.fieldName = fieldName;
    }
    
    @Column(name="PROCESS_FUNCTION", length=80)
    public String getProcessFunction() {
        return this.processFunction;
    }
    
    public void setProcessFunction(String processFunction) {
        this.processFunction = processFunction;
    }
    
    @Column(name="FIELD_LIST_ID", nullable=false)
    public long getFieldListId() {
        return this.fieldListId;
    }
    
    public void setFieldListId(long fieldListId) {
        this.fieldListId = fieldListId;
    }
    
    @Column(name="FORMAT_TEMPLATE_ID")
    public Long getFormatTemplateId() {
        return this.formatTemplateId;
    }
    
    public void setFormatTemplateId(Long formatTemplateId) {
        this.formatTemplateId = formatTemplateId;
    }
    
    @Column(name="LANG_ID")
    public Long getLangId() {
        return this.langId;
    }
    
    public void setLangId(Long langId) {
        this.langId = langId;
    }
    
    @Column(name="STATUS")
    public Long getStatus() {
        return this.status;
    }
    
    public void setStatus(Long status) {
        this.status = status;
    }




}


