package com.viettel.ocs.entity;
// Generated Sep 2, 2016 4:54:08 PM by Hibernate Tools 3.2.1.GA


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Transient;

/**
 * TriggerFieldList generated by hbm2java
 */
@Entity
@Table(name="trigger_field_list"
)
public class TriggerFieldList extends BaseEntity  implements java.io.Serializable {

	@Override
	@Transient
	public String getNodeName() {
		return null;
	}
	private Long domainId;
	@Column(name="DOMAIN_ID")
    public Long getDomainId() {
		return domainId;
	}
	public void setDomainId(Long domainId) {
		this.domainId = domainId;
	}
	 private long fieldListId;
     private Long fieldBuilderId;     
     private String fieldName;
     private Long fieldOrder;
     private Long fieldType;
     private String fieldFormat;

    public TriggerFieldList() {
    }

	
    public TriggerFieldList(long fieldListId, String fieldName) {
        this.fieldListId = fieldListId;
        this.fieldName = fieldName;
    }
    public TriggerFieldList(long fieldListId, String fieldName, Long fieldOrder, Long fieldType, String fieldFormat) {
       this.fieldListId = fieldListId;
       this.fieldName = fieldName;
       this.fieldOrder = fieldOrder;
       this.fieldType = fieldType;
       this.fieldFormat = fieldFormat;
    }
   
    @Id @GeneratedValue(strategy=IDENTITY)
    @Column(name="FIELD_LIST_ID", nullable=false)
    public long getFieldListId() {
        return this.fieldListId;
    }
    
    public void setFieldListId(long fieldListId) {
        this.fieldListId = fieldListId;
    }
    
    @Column(name="FIELD_BUILDER_ID", unique=true, nullable=false)
    public Long getFieldBuilderId() {
        return this.fieldBuilderId;
    }
    
    public void setFieldBuilderId(Long fieldBuilderId) {
        this.fieldBuilderId = fieldBuilderId;
    }
        
    @Column(name="FIELD_NAME", nullable=false, length=80)
    public String getFieldName() {
        return this.fieldName;
    }
    
    public void setFieldName(String fieldName) {
        this.fieldName = fieldName;
    }
    
    @Column(name="FIELD_ORDER")
    public Long getFieldOrder() {
        return this.fieldOrder;
    }
    
    public void setFieldOrder(Long fieldOrder) {
        this.fieldOrder = fieldOrder;
    }
    
    @Column(name="FIELD_TYPE")
    public Long getFieldType() {
        return this.fieldType;
    }
    
    public void setFieldType(Long fieldType) {
        this.fieldType = fieldType;
    }
    
    @Column(name="FIELD_FORMAT", length=80)
    public String getFieldFormat() {
        return this.fieldFormat;
    }
    
    public void setFieldFormat(String fieldFormat) {
        this.fieldFormat = fieldFormat;
    }




}


