package com.viettel.ocs.entity;
// Generated Sep 2, 2016 4:54:08 PM by Hibernate Tools 3.2.1.GA

import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Transient;

/**
 * UnitType generated by hbm2java
 */
@SuppressWarnings("serial")
@Entity
@Table(name = "unit_type")
public class UnitType extends BaseEntity implements java.io.Serializable, Cloneable {

	@Override
	@Transient
	public String getNodeName() {
		return this.name;
	}

	private Long domainId;

	@Column(name = "DOMAIN_ID")
	public Long getDomainId() {
		return domainId;
	}

	public void setDomainId(Long domainId) {
		this.domainId = domainId;
	}

	private long unitTypeId;
	private String name;
	private Long unitPrecision;
	private Long baseRate;
	private Long displayRate;
	private String remark;
	private Long categoryId;
	private Long index;
	private String abbreviation;

	public UnitType() {
	}

	public UnitType(String name, Long unitPrecision, Long baseRate, Long displayRate, String remark, Long categoryId,
			Long index, String abbreviation) {
		this.name = name;
		this.unitPrecision = unitPrecision;
		this.baseRate = baseRate;
		this.displayRate = displayRate;
		this.remark = remark;
		this.categoryId = categoryId;
		this.index = index;
		this.abbreviation = abbreviation;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "UNIT_TYPE_ID", unique = true, nullable = false)
	public long getUnitTypeId() {
		return this.unitTypeId;
	}

	public void setUnitTypeId(long unitTypeId) {
		this.unitTypeId = unitTypeId;
	}

	@Column(name = "NAME", length = 65535, unique = true, nullable = false )
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "UNIT_PRECISION")
	public Long getUnitPrecision() {
		return unitPrecision;
	}

	public void setUnitPrecision(Long unitPrecision) {
		this.unitPrecision = unitPrecision;
	}

	@Column(name = "BASE_RATE")
	public Long getBaseRate() {
		return this.baseRate;
	}

	public void setBaseRate(Long baseRate) {
		this.baseRate = baseRate;
	}

	@Column(name = "DISPLAY_RATE")
	public Long getDisplayRate() {
		return this.displayRate;
	}

	public void setDisplayRate(Long displayRate) {
		this.displayRate = displayRate;
	}

	@Column(name = "REMARK", length = 65535)
	public String getRemark() {
		return this.remark;
	}

	public void setRemark(String remark) {
		this.remark = remark;
	}

	@Column(name = "CATEGORY_ID")
	public Long getCategoryId() {
		return this.categoryId;
	}

	public void setCategoryId(Long categoryId) {
		this.categoryId = categoryId;
	}

	@Column(name = "UNIT_ORDER")
	public Long getIndex() {
		return this.index;
	}

	public void setIndex(Long index) {
		this.index = index;
	} 
	
	@Column(name = "ABBREVIATION")
	public String getAbbreviation() {
		return abbreviation;
	}

	public void setAbbreviation(String abbreviation) {
		this.abbreviation = abbreviation;
	}

	@Override
	public UnitType clone() throws CloneNotSupportedException {
		return (UnitType) super.clone();
	}

	
}
