package com.viettel.ocs.entity;
// Generated Sep 2, 2016 4:54:08 PM by Hibernate Tools 3.2.1.GA


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Transient;

/**
 * Zone generated by hbm2java
 */
@Entity
@Table(name="zone"
)
public class Zone extends BaseEntity  implements java.io.Serializable, Cloneable {

	@Override
	@Transient
	public String getNodeName() {
		return this.zoneName;
	}
	private Long domainId;
	@Column(name="DOMAIN_ID")
    public Long getDomainId() {
		return domainId;
	}
	public void setDomainId(Long domainId) {
		this.domainId = domainId;
	}
     private long zoneId;
     private Long zoneMapId;
     private String zoneName;
     private String zoneCode;
     private String remark;

    public Zone() {
    }

    public Zone(Long zoneMapId, String zoneName, String zoneCode, String remark) {
       this.zoneMapId = zoneMapId;
       this.zoneName = zoneName;
       this.zoneCode = zoneCode;
       this.remark = remark;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)
    
    @Column(name="ZONE_ID", unique=true, nullable=false)
    public long getZoneId() {
        return this.zoneId;
    }
    
    public void setZoneId(long zoneId) {
        this.zoneId = zoneId;
    }
    
    @Column(name="ZONE_MAP_ID")
    public Long getZoneMapId() {
        return this.zoneMapId;
    }
    
    public void setZoneMapId(Long zoneMapId) {
        this.zoneMapId = zoneMapId;
    }
    
    @Column(name="ZONE_NAME", length=200)
    public String getZoneName() {
        return this.zoneName;
    }
    
    public void setZoneName(String zoneName) {
        this.zoneName = zoneName;
    }
    
    @Column(name="ZONE_CODE", length=200)
    public String getZoneCode() {
        return this.zoneCode;
    }
    
    public void setZoneCode(String zoneCode) {
        this.zoneCode = zoneCode;
    }
    
    @Column(name="REMARK", length=250)
    public String getRemark() {
        return this.remark;
    }
    
    public void setRemark(String remark) {
        this.remark = remark;
    }
	@Override
	public Zone clone() throws CloneNotSupportedException {
		// TODO Auto-generated method stub
		return (Zone) super.clone();
	}




}


