package com.viettel.ocs.entity;
// Generated Sep 2, 2016 4:54:08 PM by Hibernate Tools 3.2.1.GA


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;

import java.util.Date;

import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Transient;

/**
 * ZoneData generated by hbm2java
 */
@Entity
@Table(name="zone_data"
)
public class ZoneData extends BaseEntity  implements java.io.Serializable {

	@Override
	@Transient
	public String getNodeName() {
		return this.zoneDataValue;
	}
	private Long domainId;
	@Column(name="DOMAIN_ID")
    public Long getDomainId() {
		return domainId;
	}
	public void setDomainId(Long domainId) {
		this.domainId = domainId;
	}
     private long zoneDataId;
     private String zoneDataValue;
     private Long zoneId;
     private Date updateDate;

    public ZoneData() {
    }

    public ZoneData(String zoneDataValue, Long zoneId, Date updateDate) {
       this.zoneDataValue = zoneDataValue;
       this.zoneId = zoneId;
       this.updateDate = updateDate;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)
    
    @Column(name="ZONE_DATA_ID", unique=true, nullable=false)
    public long getZoneDataId() {
        return this.zoneDataId;
    }
    
    public void setZoneDataId(long zoneDataId) {
        this.zoneDataId = zoneDataId;
    }
    
    @Column(name="ZONE_DATA_VALUE")
    public String getZoneDataValue() {
        return this.zoneDataValue;
    }
    
    public void setZoneDataValue(String zoneDataValue) {
        this.zoneDataValue = zoneDataValue;
    }
    
    @Column(name="ZONE_ID")
    public Long getZoneId() {
        return this.zoneId;
    }
    
    public void setZoneId(Long zoneId) {
        this.zoneId = zoneId;
    }
    
    @Column(name="UPDATE_DATE")
    public Date getUpdateDate() {
        return this.updateDate;
    }
    
    public void setUpdateDate(Date updateDate) {
        this.updateDate = updateDate;
    }




}


